### ISSUE TITLE
JWT

### ISSUE THREAD

**Issue by memorammstein** [gdljs/gdljs#1]
Plática para Septiembre.

**Comment by rbdr** [comment]
Sup, para la plática vamos a necesitar, al menos por ahora:

1. Título
2. Abstract (pequeña descripción)
3. Que será el demo (no necesita estár implementado aún, pero queremos saber que idea tienes del demo)
4. Cualquier otra info que creas que sea necesaria para que entendamos como va a ser la plática

:+1:

**Comment by orlando** [comment]
Closing this since this was approved :+1:
