### ISSUE TITLE
Playing D3

### ISSUE THREAD

**Issue by carlosyslas** [gdljs/gdljs#10]
Will discuss the basis of building and app with D3 by taking a look at a home made clone of Agar.io

**Comment by rbdr** [comment]
Sounds nice, more info? The demo will be the agar.io clone, and the talk will be built around how D3 makes it easy to build something like that?

**Comment by orlando** [comment]
@rbdr +1

@carlosyslas que tan agar.io clone?. Si puedes definir el scope y como este demo puede ser remixable seria cool.
