### ISSUE TITLE
Microfrontends: The Big Picture

### ISSUE THREAD

**Issue by marconi1992** [gdljs/gdljs#100]
# Microfrontends: The Big Picture (20 min)

En un mundo ágil, productos y tecnologías cambian y evolucionan demasiado rápido. ¿Cuantas veces has visto aplicaciones que han sido migradas de AngularJS a nuevos frameworks como React o VueJS? ¿Cuantas veces te has detenido para entregar nuevas funcionalidades por que dependes de otros equipos?

Microfrontends ayuda a evolucionar tu aplicación con las nuevas tecnologías y necesidades del negocio.

## Background

Mi nombre es Felipe Guizar, tengo alrededor de 5 años trabajando para big media companies, durante este tiempo he identificado algunos problemas que se pueden solucionar o mitigar con esta arquitectura. También soy el creador de [Ara](https://ara-framework.github.io/website/) un framework que ayuda a implementar Microfrontends fácilmente.

## Agenda

- Evolution of Software Architecture
- Vertical Systems
- Evolving Frontend
- Who is using it?
- Where to start?

## Take Away

En esta platica aprenderás los principios de diseño básicos, cuando si y no hace sentido implementar Microfrontends así como sus ventajas y desventajas.

## Demo

Es una lighting talk no abra tiempo para mostrar un demo. Sin embargo dejare un link a un ejemplo.

**Comment by escusado** [comment]
🍬

**Comment by sirgalleto** [comment]
Mil gracias bro
