### ISSUE TITLE
El lenguaje que nadie quería escribir

### ISSUE THREAD

**Issue by sierisimo** [gdljs/gdljs#101]
# Title

Una rapida retrospectiva al pasado (~y presente~) del desarrollo donde todo el mundo buscaba la manera de programar JavaScript sin realmente escribir JavaScript (CoffeScript,, Dart2JS, C2JS, TypeScript, GWT, ClojureScript, etc). 

## Background

Tengo ~9 años desarrollando software, mi transición fue de SysAdmin -> FrontEnd Dev -> Full Stack -> Android Dev. Esta transicion me ha dado una amplia idea de lo que cada area quiere y no quiere y como buscan mantenerse encerrados en sus cuevas sin abrirse a otros mundos.

## Agenda

1. El pasado
  * La web 2.0
  * La necesidad por JavaScript
  * Polyffills
  * Es lo que hay
2. Los competidores
  * GWT
  * JSP
  * ClojureScript
  * Ceylon
  * Dart2JS
  * CoffeeScript
3. El presente
  * Babel
  * TypeScript
  * KotlinJS
4. ¿Vale la pena seguir evadiendo a JS?
  * Conclusiones

## Take Away

Entender que partes del lenguaje eran dolorosas y como el lenguaje a evolucionado lo suficiente para poder ofrecer las mismas ventajas que tenian muchos de los lenguajes y frameworks que generaban JS.

**Comment by escusado** [comment]
😎 controversial, I like it!

**Comment by sirgalleto** [comment]
Graciaaas!
