### ISSUE TITLE
Verdaderamente serverless

### ISSUE THREAD

**Issue by sauramirez** [gdljs/gdljs#102]
# Siendo verdaderamente serverless

Esta platica trata de explicar como puedes ser realmente serverless.

## Background

Tengo experiencia trabajando en web apps por varios años y en ambientes serverless de AWS desde el inicio de Lambda

## Agenda

El contenido de la platica, puedes hacerlo algo así como un indice.

Ejemplo:

1. Que es ser serverless
  * Pequeño background de serverless
  * Que apps verdaderamente serverless podemos tener
2. Otros usos de serverless apps
  * Pensando en otro tipo de serverless apps
  * Debemos cobrar mas por realtime apps

## Take Away

El internet nos deja hacer realtime apps, la pregunta es si realmente deberiamos y porque cobramos tan poco por ello?

## Demo
TBD

**Comment by sirgalleto** [comment]
👏
