### ISSUE TITLE
Creando video juegos para feature phones con JavaScript

### ISSUE THREAD

**Issue by Fergarram** [gdljs/gdljs#104]
# Title

Un walkthrough de cómo desarrollé un video juego con JavaScript para el Nokia 8110 4G (aka Banana Phone).

## Background

Aprendí a programar desde que tengo 12 años con la intención de hacer video juegos y páginas de internet (para poner los juegos). Hoy en día soy desarrollador Frontend, y en mis tiempos libres hago pequeños juegos o experimentos, incluido este juego. Me gustaría compartir lo que he aprendido de esta nueva plataforma (KaiOS) ya que es un mercado rico y nuevo, y en un futuro no muy lejano podríamos estar dandole soporte a KaiOS junto con los demás navegadores.

## Agenda

1. El Teléfono
 * Feature Phones (Celulares como los del OXXO)
 * KaiOS — Sucesor no-oficial de FirefoxOS
 * El Nokia Banana Phone

2. El Juego
 * Forbidden Treasures (Nokia 100)
 * GM(48) Amateur Archaeology II — Game Jam Submission
 * Remake del remake

3. El Proceso
 * Hello KaiOS!
 * El PVM (Producto Viable Mínimo)
 * El "Simulador"
 * Optimizando para KaiOS

4. Los Resultados
* Publicación en la KaiStore
* Anuncios Obligatorios
* Código Abierto en Github
* Demo Público

5. QA

## Take Away

Aprender cómo desarrollar y publicar aplicaciones para KaiOS usando JavaScript.

## Demo

El juego que desarrollé está hosteado en https://fernando.works/amateur-archaeology y el código fuente se encuentra en mi cuenta de Github, aquí en https://github.com/Fergarram/amateur-archaeology.

**Comment by KarlyGrCm** [comment]
@Fergarram ping 👀
