### ISSUE TITLE
Things that help me to understand git

### ISSUE THREAD

**Issue by oscarvargas** [gdljs/gdljs#105]
# things that help me to understand git

A few tips that help me with git when i was starting and also explanations about the most common questions that the people came across when they are new at git.

## javascript developer

I have been using this technology for almost 9 years. In my previous work I realized that there were a lot of people in this area that did not understand git and they made a lot of mistakes.
I had the opportunity to give trainings and I saw a lot of things that the people used to do wrong or they did not know what they do but used anyways.

## Agenda

1. who I am?
2. What is version control system?
  * what is it 
  * what does it do ?
3. What is git?
4. what is a git tree?
5. what is a branch ?
6. kind of branches
  * Local branches
  * Remote Branches
7.  the most important tip.
8. Differences between merge an rebase 
  * Git Merge
  * Git Rebase
9. Git pull
10. The most common mistakes.
11. GUI vs Command lines.
12. QA

## Take Away

they will have more tools to deal with git situations. and they will see what thing they have to attack in order to use git properly.

## Demo

I will show a few commands that I normally use in the console.

**Comment by KarlyGrCm** [comment]
👏  Muchas gracias
