### ISSUE TITLE
Componentes con HTML y JS puros 

### ISSUE THREAD

**Issue by andreaml** [gdljs/gdljs#106]
# Title

Componentes con HTML y JS puros 

## Background

Soy Fullstack Developer, me tocó entrarle al uso de frameworks de JS donde se usa el concepto de componentes y al inicio me fue un poco complejo entender qué pasaba por dentro. Tiempo después encontré que se pueden hacer componentes solamente con HTML y JS y se me hizo súper interesante lo fácil que es digerir este concepto mediante estas herramientas. Así que si hay principiantes en este tema, esta charla les puede interesar. :D

## Agenda

1. Componentes puros
  * Qué son
  * ¿Por qué conocerlos?
  * Ventajas
4. Demo
5. QA

## Take Away

Con esta plática podremos aprender qué son los componentes web con tecnologías puras y por qué son tan útiles en nuestro proceso de aprendizaje. 

## Demo

Vamos a construir un componente reusable puro desde cero, que nos puede ayudar para generar una lista de elementos repetitivos en nuestro diseño sin necesidad de crear el mismo código múltiples veces.

**Comment by escusado** [comment]
Yeah, me gusta la idea, JS puro es cada vez menos cuando se trata de componentes!
Me preocupa que construir un componente desde cero en el Demo se vaya a comer el tiempo de 20min. de la charla. Recomendaría ver si hay chanza de que las partes que no sean tan relevantes a la explicación ya estuvieran construidas para tener tiempo de mostrar mejor el ejemplo de la lista 👌

**Comment by andreaml** [comment]
@escusado Se puede dejar hecho en el repo una carpeta con un ejemplo hecho y otro con todo listo para conectarse (el esqueleto HTML, un poco de CSS y código JS base) y terminar de construirlo en el demo. ¿Qué tal esa opción?

**Comment by andreaml** [comment]
También se me ocurre tener un CodeSandbox listo, así he manejado otras charlas que he dado. Me puedo adaptar al modo de operación de la comunidad :D

**Comment by escusado** [comment]
@andreaml Ufff ambas ideas son perfectas!!! 😎 Me gusta la idea del sandbox, creo que sería más fácil para los asistentes seguir un `fiddle` link (o alguno de esos) que descargar un zip.

**Comment by andreaml** [comment]
Sandbox será, en cuanto tenga listo el demo se los haré llegar para que quede completa la info por este medio. ¡Muchas gracias por la oportunidad!
