### ISSUE TITLE
[TBD] Conociendo VIM 

### ISSUE THREAD

**Issue by pekosoG** [gdljs/gdljs#107]
# Conociendo VIM 

Platicar como va mi relación de descubrimiento con VIM

## Background

Poca, realmente estoy aprendiendo a usarlo gradualmente, pero he encontrado dos-tres takeaways que podrían servir para predicar la palabra (wololo). De ahí en mas, estaría apuntando más a todos los niveles, nada muy específico. 

## Agenda

- VIM? 
- Porque VIM?
- Resumen de la historia de VIM (Quizá mencione NeoVim un leve aqui)
- Pros/Cons que he encontrado
- Mi plan para aprenderlo
- But Why? (Mi percepción/opinión hasta ahora)
- Comando Básicos/Demo?

## Take Away

Intentar perderle el miedo y conocerlo en modo útil, no solamente por los memes.

## Demo

Not quite sure yet, quizá un par de comandos básicos de movimientos con el cursor y el cambio de modos.

Quizá arreglar un pedacito de código super rápido 🤔

**Comment by sadotsoy** [comment]
💘
