### ISSUE TITLE
UI for Angular haters

### ISSUE THREAD

**Issue by escusado** [gdljs/gdljs#11]
### Intro
Using a coding pattern closer to the UI mental abstraction and removing most of the features many front-end frameworks have, the `Widget` approach propose a hierarchy driven abstraction and DOM relatable components. In this talk I want to share my favourite patterns and architecture approach to defining UI with the goal of reducing complexity and external dependencies.

---

### Why you want to give this talk (goal for the end user):
- Architecting UI over heavy frameworks is getting more popular as these big codebases get adopted. I want to present an alternative, opinionated and simpler way of coding UI based on the `Widget` library.

### Presentation content (Short brief and topics you will talk):
- How do we design UI?
- How do we Architect UI if frameworks didn't exist?
- Al natural: DOM, CSS, JS
- Component based systems (web components)
- The UI problems: Storage, Communication, Hierarchy.
- The minimum usable UI component?
- Lets use es6

### Demo content (Features it will have):
- Fortune telling machine? (TBD but should be a basic HTML form + some visual feedback using a `<canvas>`  view)

### Is the demo "remix-able" (can the user extend it easily?):
- npm installable libs to use `Widget` with es6
- An extendable basic boilerplate~ish `Widget` app

**Comment by orlando** [comment]
closing
