### ISSUE TITLE
MeteorJS no está muerto, pero tampoco andaba de parranda.

### ISSUE THREAD

**Issue by ackzell** [gdljs/gdljs#111]
# Title

MeteorJS no está muerto, pero tampoco andaba de parranda.

## Background

No me considero un desarrollador de Meteor como tal (léase no soy experto en el tema), pero me gusta mucho la idea y lo he seguido como observador desde su origen hasta hoy en día.

## Agenda

1. ¿Qué cosa?
  * Qué es, de dónde salió y ¿Cómo que no andaba de parranda?
  * Quién o dónde se utiliza
  * Un par de datos curiosos alrededor de la tecnología
  * Recursos para aprender más, la comunidad que existe
2. La parte más técnica (tal vez como live coding desde aquí)
  * ¿Cómo creas una app desde 0?
  * ¿Qué framework de UI puedes usar con él?
  * Code walkthrough de una app en Meteor.
 3. Las partes que no tengo muy claras, pero sé que se pueden (ven que no soy experto?)
  * Integración con otras tecnologías
  * Deployment
5. Q&A (haré lo mejor que pueda)

## Take Away

Sí, es oootro framework del que puedes echar mano. Tal vez tengas mejores ideas que yo de en qué se puede utilizar y cuándo te resultaría útil apoyarte en él. Saber que existe creo que ya es suficiente ganancia. 

Ojalá que ya todos sepamos que no es una bala de plata y que no la podremos encontrar en ningún lugar, pero que al terminar la charla tengas una idea suficientemente buena de qué se trata y dónde puedes encontrar más información al respecto.

## Demo
Una app que echa mano de varios de los conceptos que platicamos durante la charla, la misma a la que le hicimos el recorrido juntos durante la misma.

**Comment by KarlyGrCm** [comment]
Gracias por tu charla @ackzell  🎉
