### ISSUE TITLE
Plus Codes, please

### ISSUE THREAD

**Issue by dezkareid** [gdljs/gdljs#113]
# Title
Plus codes, please

Los Plus codes nos ayudan a definir direcciones o areas calculadas en base a las coordenadas geográficas de un punto. Esto permite ubicar lugares donde no existe una dirección física definida. 

## Background

Google Developer Expert en Maps y amante de la visualización de datos. Para mas detalles revisar este [post](https://medium.com/@DezkaReid/plus-codes-please-bc4de5ff3e1b)

## Agenda

1. ¿Plus codes?
  * Ejemplos de uso
  * Estructura
  * Bibliotecas
2. Google Maps y Plus Codes
3. Demo
4. QA

## Take Away

Aprenderán que son los plus codes, como están estructurados, como se pueden usar y como pueden integrarlo en sus proyectos

## Demo

Un mapa que tiene soporte para usar plus codes para buscar lugares

**Comment by JoseJesusOchoaTorres** [comment]
Esa es Joelon, buena propuesta de charla; ya paso o esta por pasar? @dezkareid

**Comment by KarlyGrCm** [comment]
hable con @dezkareid voy a reabrir esto cuando el tenga un poco mas de disponibilidad
