### ISSUE TITLE
Grid systems origin, evolution and status

### ISSUE THREAD

**Issue by JoseJesusOchoaTorres** [gdljs/gdljs#114]
# Grid systems status

Quiero explicar, que son los grid systems, su origen, evolución y estado actual.

## Background

Tiempo atrás cree mi propio grid system, he construido un CSS framework dentro de un equipo en IBM y estoy iniciando a colaborar para el design system de [Carbon](https://www.carbondesignsystem.com/). 

## Agenda

1. Que es un design system
  * Definición
  * Origen
  * Uso

2. Evolución
  * Tables
  * Floats
  * Flex
  * Grid

3. Estado actualidad
  * CSS in JS
  * Web components 
  
4. Cuando si y cuando no usarlos

5. Colaborar en comunidad

## Take Away

- Que es un grid system
- Como se usan
- Por qué se usan
- Cuando se usan
- Cuando no se usan
- Cómo se construyen

Al mostrar todos estos temas, las personas inician a comprender cómo funciona algo que usan en su día a día y por consecuencia, se sienten un poco más motivados para iniciar a trabajar en proyectos open source. Es importante demostrarles que cualquier developer puede comprender el código fuente de herramientas que usamos en nuestro dia a dia solo analizando cómo funcionan estos mismo. Las primeras veces pueden parecer más complejas de lo que realmente son.

## Demo

No hay un demo como tal, pero este pequeño proyecto de ejemplo puede ayudar a complementar mi presentación.

https://josejesusochoatorres.github.io/another-css/#/
https://github.com/JoseJesusOchoaTorres/next-portfolio/blob/master/assets/css/modules/_mixings.scss

**Comment by KarlyGrCm** [comment]
Gracias otra vez @JoseJesusOchoaTorres 👏
