### ISSUE TITLE
@skelogh/weaver - Migrating easily NoSQL docs based (or not) on the extended reference pattern.

### ISSUE THREAD

**Issue by SkeloGH** [gdljs/gdljs#115]
# Title

[@skelogh/weaver](https://www.npmjs.com/package/@skelogh/weaver) - Migrating easily NoSQL docs based (or not) on the extended reference pattern.

## Background

Often times when working with NRDBs like MongoDB, documents reference to other documents from different collections, databases, or even database types. This becomes a challenge when trying to replicate an existing -intertwined- dataset to be used in a different environment.

## Agenda

1. Working with NoSQL
  * Why do we use it?
  * Example use case
2. The extended reference pattern
  * Definition and use case
  * Other patterns (over the top)
3. Challenges when using NRDB with ERP
  * Example: teechip.com
4. Introducing: `weaver`
5. Demo
6. QA

## Take Away

We'll learn about a few NoSQL model design patterns, specifically the ERP, we will also save time when cloning data by using a tool built for it.

## Demo

- Install [the npm package](https://www.npmjs.com/package/@skelogh/weaver).
- Add and remove clients.
- Clone data using the tool.
- If time allows, showcase [the project journey](https://github.com/SkeloGH/weaver/projects?query=is%3Aclosed%2Copen).

**Comment by KarlyGrCm** [comment]
Thanks a lot @SkeloGH 🎉
