### ISSUE TITLE
A web for everyone, web accessibility

### ISSUE THREAD

**Issue by arathjz** [gdljs/gdljs#116]
# Title

A web for everyone, web accessibility

Have you ever wondered how people with disabilities interact with the web? Sometimes they have a really bad time when trying to navigate throughout the web

## Background
I'm currently a software engineer in Codelitt, I've been working with web applications as a frontend developer for about 2 years. Recently, I've been interested in learning how to improve the accessibility of the applications I build, I'd like to share with the community what I have learned about this subject.

## Agenda
* What is web accessibility?
* Types of disabilities
* Keyboard Navigation
* Screen readers
* Semantic HTML

## Take Away
 This will be a talk to introduce you to web a11y and why it’s important to build accessible applications

## Demo
https://docs.google.com/presentation/d/1Uxx-IJ4Hwg4kvOypqBmlID3zcl3qxm0EsgyGKvTxMsA/edit?usp=sharing

**Comment by KarlyGrCm** [comment]
🥇
