### ISSUE TITLE
Layout components: A whole new world

### ISSUE THREAD

**Issue by TheMightyPenguin** [gdljs/gdljs#117]
# Layout components: A whole new world ✨ 

El otro dia me dio curiosidad que tanto reusabamos Layouts en mi proyecto actual. Hice un global search por `display: flex;`, y aparecieron 300+ resultados 😲 . Estaba claro que teniamos un problema, porque teniamos abstracciones para cosas como botones, o componentes mas atomicos, pero no para Layouts? Como podemos arreglar esto? Que abstracciones podrian ayudarnos a resolver el problema?

En esta platica vamos a responder estas preguntas con teoria y ejemplos practicos!

## Background

He tenido este problema en varias ocasiones en distintos equipos, y en conjunto con mi equipo hemos definido componentes que abstraen los problemas de layouts mas comunes que tenemos, y con esto hemos mejorado nuestra eficiencia y reducido el codigo duplicado. Es un tema que me apasiona mucho, y son patrones que opino que nos ayudan muchisimo en el mundo del frontend, y que apenas estamos descubriendo!

## Agenda

1. Que es Layout?
2. Cual es el problema al implementar layouts?
3. Layout Components
    * Que son?
    * Como resuelven el problema
    * Ejemplo!!
4. Que beneficios tiene usar estos componentes
5. Donde puedo encontrar inspiracion?
    * Donde podemos inspirarnos para aplicar estos patrones?
    * Que librerias o Design Systems open source podemos observar?
6. QA

## Take Away

Como podemos abstraer nuestros layouts a componentes, y como este patron nos ayuda a:

* Reducir el codigo de nuestra aplicacion
* Ser mas productivos cuando tenemos que implementar una UI
* Mejorar la colaboracion entre diseñadores y developers
* Reducir la cantidad de CSS que alguien debe saber para contribuir al proyecto
* Como encajan los Layout components dentro de un Design System

## Demo

El demo sera un playground que muestra distinto patrones de layouts ya implementados, y podemos jugar con distintos valores para entender como funcionan. **Coming soon 😜**

**Comment by sirgalleto** [comment]
@TheMightyPenguin cuándo crees poder dar la plática?

**Comment by TheMightyPenguin** [comment]
@sirgalleto para el GDLJS de febrero se podria? 😄

**Comment by sirgalleto** [comment]
Si!

**Comment by KarlyGrCm** [comment]
Hey muchas gracias @TheMightyPenguin 🎉
