### ISSUE TITLE
Using Google Script to fight COVID

### ISSUE THREAD

**Issue by aromeronavia** [gdljs/gdljs#119]
# Title
Using Google Script to fight COVID

## Background
En momentos de mucha improvisación, la [Unidad Covid Citibanamex](https://www.centrocitibanamex.com/prevaloracion/) empezó a guardar datos de sus pacientes sobre Excel, debido a ciertos problemas de usabilidad con otros sistemas internos y la experiencia digital de algunos doctores y enfermeros voluntarios.
La situación se veía problemática conforme iban escalando su numero de columnas por pacientes, creando nuevos sectores (contenedores de camas), diferentes tipos de sectores, etc.

## Agenda
1. Explicar problema y contexto
2. Discovery phase para mitigar el problema
3. Google Script. ¿Qué es eso?
4. Explicar un poco el API de Google Script, qué se puede hacer y cómo?
5. Seleccionar Celdas, Copiar y Pegar.
6. Resultados en la unidad covid!
7. Demo

## Take Away
Entender lo básico para desarrollar un script sencillo en Google Script.

## Demo
El excel de prueba que usé (sin datos sensibles, datos dummys) para hacer las pruebas. Ejemplo bastante sencillo.

**Comment by KarlyGrCm** [comment]
@beeetooo ping 👀

**Comment by aromeronavia** [comment]
Se me fue por completo esto 👀  voy a cerrar el ticket y abrir otro para compensar 🙌
