### ISSUE TITLE
Animacion en JS

### ISSUE THREAD

**Issue by striwensko** [gdljs/gdljs#12]
Usando un framework que estara open source, se mostrara como hacer animaciones sin tener que escribir practicamente codigo alguno, sino usando solamente la descripcion de la animacion en formato JSON. El framework usa css tranforms y requestAnimationFrame lo cual lo hace correr eficientemente en tablets y celulares. Se explicara las ventajas de usar css transforms en vez de propiedades como left, top, width, height. El framework no tiene depencia alguna por lo que no deberia tener ningun problema en ser usado con otros frameworks, ya que lo unico que necesita es la referencia del elemento html a animar.

**Comment by rbdr** [comment]
Me gustaría que en lugar de enfocarse en como programar en el framework, porque fue diseñado como fue diseñado. Por ejemplo eso que mencionas de las ventajas de usar css transforms.

Como sería el demo, vi este link: http://priority.widgetmatic.com/ad/FULL_DEMO.html que pusiste en slack, pero no me funca

**Comment by striwensko** [comment]
Entras al link y solito se corre una animacion no ves la animación cuando entras al link que mande?

**Comment by rbdr** [comment]
LOL olvidalo estoy bien wey. Fue mi adblocker. Thoughts? @orlando @escusado?

**Comment by escusado** [comment]
Está chida, y simon echo de rbdr, más que "como usar la lib", explica mejor por que creaste una lib así.

- que tiene esta que no tienen las otras
- que problema en particular pretendes resolver 
- y cual es el futuro para la lib (si es que lo hay pues)

No hables del framework, habla del problema que pretendes resolver y luego presenta el framework que lo resuelve y ahora si las ventajas y tal.

**Comment by rbdr** [comment]
Simont, menos código/técnico. Pues yo digo que está on para Enero.

**Comment by striwensko** [comment]
Ok me parece bien, esta tenica con la que hice este yo creo mas que framework es un engine, surgio hace 10 años para hacer animaciones de graficas de barras para flash, y la razon de la creacion de este codigo fue para hacer animaciones facilmente para personas que no saben programar. De hecho pues tiene su historia todo esto desde sus inicios en flash, su cambio a javascript, y su pulida con el uso de css transforms, y requestAnimationFrame en vez del usual setInterval y top,left que fue lo que usaba cuando recien lo traduje a js.

**Comment by orlando** [comment]
closing
