### ISSUE TITLE
Probando Mal. Cómo empeorar las cosas y seguir contento.

### ISSUE THREAD

**Issue by rbdr** [gdljs/gdljs#120]
# Probando Mal. Cómo empeorar las cosas y seguir contento.

Una historia en 4 partes sobre como aprender a probar, como perder el hilo de lo que estabamos tratando de lograr con las pruebas, las buenas prácticas que nos llevaron a ese punto y un final feliz con recomendaciones para no tener que mantener 12 millones de líneas de código en pruebas

## Background

Autoridad: He escrito más de doce pruebas, he escrito pruebas de mala forma, y luego borré todo. Luego escribí menos pruebas.

## Agenda

Ejemplo:

1. Comienzo
  * El camino a empezar a probar
  * Overview Buenas prácticas
2. Desdicha
  * Buenas imprácticas
  * Llanto
3. Viraje
  * Un acto de desesperación
  * Nuevas prácticas, menos pruebas
4. Resultados
  * Un resumen de lo que aprendí
  * Mucho hate hacia las e2e tests

## Take Away

Hay que escribir menos pruebas (probablemente)
Muchas pruebas no sirven (probablemente)
No hay una buena razón para mantener e2e tests (sin excepciones)

## Demo

No hay Demo, pero en mi mirada sin esperanza ni sueños podrás observar el daño que hice al tratar de probar cosas de la manera incorrecta.

**Comment by KarlyGrCm** [comment]
🥇
