### ISSUE TITLE
Web3 <> JS

### ISSUE THREAD

**Issue by lcamargof** [gdljs/gdljs#124]
# Web3 <> JS
Pequeña introduccion a web3, fundamentos generales y como se usa javascript para desarrollo de DApps

## Background
Blockchain en general es un topic que esta en auge y cada dia hay mas DApps en la red, actualmente me encuentro trabajando en un proyecto de DeFi y soy el encargado del desarrollo de la DApp, entre sin bases en el blockchain y estos ultimos meses han sido una jornada de aprendizaje en todo este ambiente que me gustaria compartir.

## Agenda
1. Web3
- Pequeño overview de como funciona el blockchain especificamente Ethereum
- Que es y como se usa en la actualidad
2. Dapps
- Pequeño ejemplo de una DApp
- Desafios que se encuentran al trabajar en dapps
3. IPFS / theGraph and beyond 🚀 
QA

## Take Away
Entendimiento de como funciona web3 y como comenzar a indagar en este ambiente.

## Demo
TBD - Probablemente un ToDo list o counter en ethereum.

**Comment by KarlyGrCm** [comment]
@lcamargof 👀  ping

**Comment by lcamargof** [comment]
@KarlyGrCm si es presencial si 😉

**Comment by KarlyGrCm** [comment]
Muchas gracias again @lcamargof te rifaste 👏
