### ISSUE TITLE
Animaciones chidas con GSAP

### ISSUE THREAD

**Issue by arelsirin1** [gdljs/gdljs#125]
# Title

Animaciones chidas con GSAP (https://greensock.com/gsap/)

## Background

Hace algunos años un cliente solicitó en un proyecto construir animaciones similares a las del sitio oficial de Apple. Nos volvimos un poco locos hasta que encontramos GSAP que nos ayudó un montón a desarrollar las animaciones con facilidad y terminamos desarrollando expertise con la herramienta.

## Agenda

1. Animaciones Web
  * Ejemplos de sitios con animaciones sorprendentes.

2. GSAP Introduction
  * Que es GSAP?
  * Ejemplos de animaciones logradas con GSAP
  * Detalle de implementación de una homepage animada con GSAP
  * GSAP API documentation

3. GSAP Community
  * GSAP contribution
  * GSAP forums
  
## Take Away

Una introducción técnica a GSAP sumado a una demostración de las distintas animaciones que se pueden lograr con la librería.

## Demo

Tendremos un sitio que tendrá su homepage animada con GSAP, podemos interactuar realizando cambios en vivo sobre las animaciones.

**Comment by KarlyGrCm** [comment]
😮  nunca habia escuchado de esta herramienta, nice! espero ver la charla pronto 👀

**Comment by KarlyGrCm** [comment]
🎖️
