### ISSUE TITLE
Aprendiendo a tocar guitarra con WebAudio API y Nuxt/Netlify

### ISSUE THREAD

**Issue by aromeronavia** [gdljs/gdljs#126]
# Title
Aprendiendo a tocar guitarra con WebAudio API, Nuxt/Netlify y más amigos

## Background
Soy guitarrista desde hace 15 años, aprendí a tocar la guitarra de oído y nunca tuve una educación formal. A inicios de 2021 empecé a tomar cursos con un profesor de guitarra y me empezó a enseñar a utilizar escalas de guitarra que no conocía (Jónico, Dórico, Eólico, Lidio, Mixolidio, Friggio, Locrio, Escala Menor Harmónica, etc etc).
Dado que cada escala es una variación de intérvalos (distancias entre notas), decidí construirme una herramienta para poder improvisar y tocar solos de guitarra dependiendo de la escala que eligiera. Así nació [Explore the Fret](https://explorethefret.com/)

## Agenda
1. Introducción a Notas y Escalas musicales
2. Empezando el proyecto
3. Web Audio API, lo más básico para explicar la solución
4. Netlify, continuous deployments para calar cambios rápido
5. Demo

## Take Away
Usar tecnología para ayudarte a ti mismo a aprender o hacer tu vida más fácil en cualquier ámbito es cool 🌠 

## Demo
Aquí anda el tool https://explorethefret.com

**Comment by KarlyGrCm** [comment]
@aromeronavia ping 👀

**Comment by aromeronavia** [comment]
@KarlyGrCm pong

**Comment by aromeronavia** [comment]
Me avisan cuándo se arma el acá y armo los slides 🚀
