### ISSUE TITLE
Javascript en la web 3.0, construyendo una DApp

### ISSUE THREAD

**Issue by OscarCode9** [gdljs/gdljs#127]
# Title
Javascript en la web 3.0, construyendo una DApp

## Background

He estado trabajando en los últimos 5  años con javascript, en tecnología tanto en el backend como en el front, y actualmente desarrollando conocimiento en el blockchain para tecnología descentralizada y trabajdo como desarrollador en https://densitylabs.io/

## Agenda

1. Las web 3.0 y la web decentralizada
 *  Que es la web 3 y el mundo decentralizado 
2. Solana blockchain
 * Como funciona el blockchain y como utilizar JavaScript  con solana blockchain 
3. Tokens con JavaScript
 * Como crear tu propio token, hacer transacciones
4. Demo
 * Sistema de pagos por medio de tokens (javascript, solana, web3 , react) 
 
## Take Away

Se aprenderá como se puede implementar javascript para la creación de una aplicación decentralizada por medio del blockchain de solana

## Demo

System de pagos por medio de tokens

**Comment by KarlyGrCm** [comment]
Hola @OscarCode9 ! Oye desafortunadamente ya tenemos otra charla registrada con la misma tematica #124. Voy a cerrar este ticket pero sientete libre de abrir un nuevo issue con un tema distinto :)
