### ISSUE TITLE
Programación funcional con JS

### ISSUE THREAD

**Issue by jorgevgut** [gdljs/gdljs#13]
Esta plática aún es una propuesta, ya sé de varios puntos que quiero cubrir, pero aun así quisiera pedir su feedback.

Javascript - lenguaje de programación "multiparadigma", pero.. ¿aprovechamos las facultades que nos ofrece?
La idea de esta plática es hacer una introducción no solo al paradigma de programación funcional y como se puede utilizar en Javascript. Y como se utiliza con librerías de JavaScript populares como d3 y react.
Propuesta de algunos temas/conceptos a cubrir:
- Definir que es una función.
- Propiedades de funciones puras en programación.
- Arrow functions / lambdas
- Ventajas y casos de uso de este paradigma con Javascript.
- Funcional vs POO

Propuesta de ejemplos (lo que subiría a GitHub):
- Ejemplos sencillos que utilicen los métodos forEach(),map(), filter(), reduce() de Array.
- Ejemplos utilizando Arrow functions (lambdas).
- Ejemplos sencillos de como d3js implementa el paradigma funcional en sus componentes.
- Ejemplos sencillos de como integrar el paradigma funcional incluso en objetos(classes). 
- Comparativas entre diferentes estilos de programación.
- Posiblemente ejemplos usados en conjunción con react.

Por si las moscas estoy en twitter: @jorge_vgut

**Comment by rbdr** [comment]
Se ve bien el tema en general, pero en lugar de hacer un demo que sean problemas pequeños, creo que estaría mejor donde fuera un proyecto pequeño donde se usan esos conceptos de manera práctica. La idea es tratar de hacer las pláticas de forma en que se enfoquen en el problema que resuelven, como nos hace pensar diferente, etc. Y que el demo sea una forma de ejercitarlo practicamente. Ejemplos sencillos de los conceptos los podemos googlear, pero algo más completo creo que ayudaría más a que podamos entender porque deberíamos usarlo.

**Comment by xymind** [comment]
Ah listo Ruben, creo que entendí mal esta parte del que se necesita para dar una plática "eso tratamos de que el contenido de la plática no se vaya muy profundo en el código: con algunos ejemplos es suficiente". Entonces Con ejemplos  se refiere a algo un poco mas complejo, ni tan sencillo pero no tan a fondo?
En ese caso la propuesta seria trabajar con una aplicación en express levantando unos servicios para regresar jsons. Y manipularlos utilizando código que cae dentro del paradigma, y me quedaría con lo d3js también.

**Comment by orlando** [comment]
@xymind any update on this?

**Comment by orlando** [comment]
Cerrando por falta de actividad

**Comment by svzosorio** [comment]
Lástima, se veía buena la plática. Estaría bien reactivar la propuesta.

**Comment by orlando** [comment]
@svzosorio @jorgevgut todos los issues los pueden reabrir con solo comentar. Pero el que va a dar la platica debería hacerlo.

Cuando cerramos un issue por inactividad no es que no puedas dar la platica, es solo para tener el menor numero de issues abiertos en el repo.

**Comment by orlando** [comment]
@jorgevgut @svzosorio voy a reabrir este issue esperando que se anime

**Comment by rbdr** [comment]
@jorgevgut hay update?

**Comment by jorgevgut** [comment]
@rbdr sorry no he tenido updates en mucho tiempo porque tenia que organizar mi boda.. ya me case en Julio asi que si aun hay interes la puedo retomar. T___T comprendo si nos e puede, tarde mucho en responder.

**Comment by rbdr** [comment]
Felicidades! Reabriendo el issue \m/

**Comment by sirgalleto** [comment]
@jorgevgut Felicidades 🎉

**Comment by orlando** [comment]
@jorgevgut algun update por aca?

**Comment by orlando** [comment]
Closing por inactividad, feel free to reopen el issue si quieres dar la platica
