### ISSUE TITLE
AWS Amplify para el desarrollo de aplicaciones web y movil

### ISSUE THREAD

**Issue by Fitux** [gdljs/gdljs#130]
# Title

Esta es una platica que trata del framework Amplify de AWS y como se puede usar para desarrollar de manera rapida aplicaciones donde el enfoque esta principalmente en el Front-End y no se quiere perder tiempo en la parte de Back-End.

## Background

Trabaje alrededor de un año desarrollando una plataforma sobre los servicios de AWS amplify

## Agenda

1. Introduccion a AWS Amplify
  * Que es AWS Amplify
  * Ventajas y desventajas
2. Development Features
3. CI/CD Features
4. Demo
5. Q&A

Algunos extras si se tiene tiempo de sobra

6. Cuando usar y cuando no usar AWS Amplify
7. Other specialized features

## Take Away

Van a aprender a utilizar Amplify como una herramienta para el desarrollo y poder levantar una aplicacion sencilla en esta plataforma, que ventajas tiene y en que situaciones les puede servir para desarrollar nuevas aplicaciones.
Ademas de que sabran de todos los posibles features que les ayudaran para que esa aplicaciones sean lo mas completas posibles

## Demo

El demo sera una pequena practica donde se creara un aplicacion base de react la cual se usara para levantar un proyecto en Amplify, y se agregaran algunos de los features mas importantes de amplify para demostrar como se usarian de manera basica y lo sencillo y rapido que es implementarlos.

**Comment by pekosoG** [comment]
Suena bastante interesante, pero crees que hablar de todos los temas + demo si quepa en los 20mins? 👀

**Comment by Fitux** [comment]
Si la verdad planeaba hablar por unos 5 o 10 mins, los features en general es nomas tocarlos muy a alto nivel nomas explicar que son y para que sirven, en si dar un overview general de las capacidades que se tienen al elegir Amplify y ya tomar el resto del tiempo en el demo demostrando implementar ejemplos de algunos de los features mas importantes, ya que no creo alcanzar a hacer un demo de todo lo que se puede locar

**Comment by KarlyGrCm** [comment]
Ea, muchas gracias! 🏅
