### ISSUE TITLE
Un viaje en el tiempo con JS

### ISSUE THREAD

**Issue by arturomc** [gdljs/gdljs#131]
# Un viaje en el tiempo con JS - La evolución de los problemas que resolvemos y el como los abordamos

Hoy en día, donde es normal navegar la web al menos una vez al día, resolver dudas inmediatamente en lugar de quedarnos con ellas, tener miles de pesos invertidos en NFTs y pedirle a una AI que te recomiende código mientras lo escribes, es fácil olvidar que en los últimos 120 años de historia humana cambiamos de barcos de vela a naves espaciales y en solo un cuarto de ese tiempo, la web nació y ha evolucionado de una manera tan impactante en la vida humana y avanzado tan vertiginosamente rápido a las varias piezas que la componen hoy en día. 

Esta platica es una recapitulación del problema que hemos resuelto en la web, su evolución y la manera en que nos hemos adaptado para resolverlo desde el punto de vista de un pequeño lenguaje de scripting que pudo.

## Background
Soy un "nerdazo" del desarrollo de software y de la historia en general, llevo 15 años desarrollando en varios lenguajes, investigando trends , "fanboyeando" con librerías y frameworks, experimentando y colaborando en librerías y frameworks en código abierto. 

También grabo un podcast de desarrollo web en español, my typeof radio y lidero la organización de ingeniería de Javascript en Improving.

## Agenda
1. Primera parada: Desde Tim Berners-Lee hasta John Resig, pasando por Luis Miguel.
2. Segunda parada: El nacimiento de la arquitectura de nube, el regaeton y la guerra de los frameworks.
3. Tercera parada: El presente, seguridad, todo micro, todo basado en eventos, componentes y K-POP.

## Take Away
La manera en que ha evolucionado el problema que abordamos y el como lo resolvemos como desarrolladores nos ayuda a entender que hay detrás de muchas decisiones técnicas que tomamos o no hoy en día, sobre que cimientos se construye el nuevo software y como utilizarlos hoy para crear soluciones diferentes.

## Demo
No estoy pensando en mostrar un demo, pero tal vez muestre código en un servidor ligero en node sirviendo estáticamente algunos ejemplos de las maneras pasadas de escribir web.

**Comment by KarlyGrCm** [comment]
Muchas gracias @arturomc 👏
