### ISSUE TITLE
Robots para el fin del mundo

### ISSUE THREAD

**Issue by escusado** [gdljs/gdljs#132]
# Title

PS5, Robots & Javascript

## Background

Los problemas que me he encontrado tratando de mover un robot con controles de ps5 y javascript 

## Agenda

1. Project Overview
2. Plan
3. Donde estoy
4. node + adafruit + linux
5. PS5 Controller y sus pedos con node
6. jstest
7. Further improvements

## Take Away

Se llevan un primer de cómo usar una raspberry pi, de cómo controlar motores, de cómo leer outputs de otros programas.

## Demo

Un link al repo donde está todo, con el explicación de como vamos

**Comment by KarlyGrCm** [comment]
Master toy rifado como siempre 🔥
