### ISSUE TITLE
Redis 101

### ISSUE THREAD

**Issue by jsedano** [gdljs/gdljs#136]
# Redis 101

Redis nos ofrece un cache en memoria, una base de datos no relacional y otras cosas mas, para que casos de uso lo podemos usar, con que extensiones cuenta, como se escala y como usarlo en la nube es lo que veremos brevemente.

## Background

Trabaje un poco con Redis en el pasado e hice una entrada para un hackathon de redis en dev.to https://dev.to/jsedano/removies-599a y he hecho un par de posts en mi blog:

https://jsedano.dev/redis/2022/09/17/redis-2022.html
https://jsedano.dev/java,/redis/2022/09/19/java-redis-pub-sub-example.html

## Agenda

El contenido de la platica, puedes hacerlo algo así como un indice.

Ejemplo:

1. what is redis ? 
  -  breve explicación acerca de redis 
2. supported data types
  - tipos de dato soportados
3. special use case types
  - tipos de datos especiales 
4. additional support
  - extensiones como redisJSON, bloom, redisInsights etc.
5. redis on the cloud
   - soporte para redis en la nube
6. redis cluster
   - formas de escalar y asegurar HA
   
## Take Away

Que es redis mas halla de un solo cache en memoria, que tipos de datos soporta, como se escala, en que nubes se puede ocupar.

## Demo

se presentara una instancia de redis corriendo la cual se puede instalar usando docker https://docs.redis.com/latest/ri/installing/install-docker/

**Comment by KarlyGrCm** [comment]
Muchas gracias @jsedano 🙌
