### ISSUE TITLE
Prisma - ORM de próxima generación

### ISSUE THREAD

**Issue by ushieru** [gdljs/gdljs#138]
# Prisma - ORM de próxima generación para Node.js y TypeScript

A lo largo de los años, han surgido muchos ORM populares, pero hoy vamos a hablar de Prisma: un ORM de proxima generacion. El cual se ha convertido en una alternativa popular para desarrolladores de todo el mundo. Prisma es fácil de configurar y utilizar, proporciona una API sencilla y eficiente para interactuar con bases de datos de cualquier tamaño y complejidad.

## Background

Soy Uziel Cocolan, mejor conocido como "Ushieru" en internet. Ingeniero de Software en IBM de profesion, profesor de ingenieria en la universidad de especialidades por vocación. Tengo 5 años desde que empece a ganarme la vida escribiendo código.

## Agenda

1. Introduccion
  * Que es un ORM?
  * Que es Prisma?
2. Como funciona?
  * Con que bases de datos lo puedo usar?
  * Como se definen los modelos?
  * Tengo control de migraciones?
  * Puedo configurar un seed?
3. Prisma es para mi proyecto?
  * Funciona para proyectos nuevos?
  * Funciona para proyectos viejos?
  * Se puede integrar con mi framework favorito?
4. Que cliente uso para mi base de datos?
  * Prisma Studio
5. Demo
6. QA

## Take Away

Que es y como usar los aspectos básicos de Prisma para implementarlo en proyectos viejos y nuevos.

## Demo

[Koa - RESTAPI CRUD example](https://github.com/ushieru/todo-crud-prisma)

**Comment by KarlyGrCm** [comment]
👏 super bien, te late te agendo para marzo?

**Comment by ushieru** [comment]
Claro, quedo al pendiente de la fecha en concreto. Mil gracias.
