### ISSUE TITLE
[CHARLA] Web 3.0 | Construye una internet descentralizada con Js

### ISSUE THREAD

**Issue by izcc** [gdljs/gdljs#139]
# Web 3.0 | Construye una internet descentralizada con Js
Descubre el uso de la tecnologia blockchain y como Javascript ha catapultado un desarrollo rápido y moderno para la construcción de soluciones solidas como smart contracts. 

## Background

Hola, Soy Irving Cancino. Tengo 5 años en la educación tecnologica, soy profesor Lv2 de Google, entusiasta blockchain, NEAR Certified Professor ⋈, construyendo para  y colaboro con la comunidad dev del [@openwebacademy_](https://twitter.com/openwebacademy_). Desde hace algunos meses soy un hippie del internet, amante dle software libre y las tecnologías descentralizadas. Veamos que siempre hay una segunda opción, incluso en la tecnología ;)

## Agenda

1. Web 3.0 y Blockchain
  * De la web 1.0 a la 3.0
  * Cómo funciona la cadena de bloques
  * Mecanismo de consenso
  * Pros y contras del blokchain
2. Protcolo de NEAR
  * Para que sirve y que podemos hacer con el
  * Herramientas de desarrollo de NEAR
  * ¿Descentralización?
3. Js para la blockchain
  * SDK
  * Ventajas de Js en NEAR Protocol
  * Como hacer tu primer dApp
4. Demo
5. QA

## Take Away

Los asistentes conocerán una nueva opción para el desarrollo de aplicaciones, distinta al Cloud Computing, tendrán la oportunidad de  ver los beneficios del desarrollo blockchain y las diferencia respecto a las cryptomonedas. Así como tener herramientas para iniciarse ne el desarrollo de smart contracts con Js

## Demo

[Repositorios de los diferentes demos que se mostrarán](https://github.com/open-web-academy)

**Comment by KarlyGrCm** [comment]
🎉
