### ISSUE TITLE
Aplicaciones Fullstack 100% JS en menos de 20 minutos

### ISSUE THREAD

**Issue by gaboAcosta** [gdljs/gdljs#14]
Tal vez no es la plática más técnica del mundo, pero trabajando durante un año en aplicaciones con NodeJS y con AngularJS he aprendido a utilizar de manera eficiente un generador en particular de Yeoman que me parece podría ser de mucho interés para la gente que nunca ha hecho apps en Angular o en Node.

No es nada del otro mundo, pero se daría el intro de que son los requisitos para correr la app y cual es la metodología para empezar a desarrollar una app en menos de una hora. Si es necesario puedo incluir detalles del deploy y como maneja diferentes ambientes de desarrollo.

El Scaffolding de Yeoman que se trabajaría sería el siguiente:
https://github.com/angular-fullstack/generator-angular-fullstack

**Comment by orlando** [comment]
Hey @gaboAcosta

Como oyente, que aprenderias de tu platica y por que crees que va a contribuir con la comunidad

**Comment by orlando** [comment]
Hey @gaboAcosta

Hoy agregamos un template que puedes usar para expandir un poco mas el tema y como vas a hablar de el, por favor cambia este issue para que siga ese formato https://github.com/gdljs/gdljs/blob/master/ISSUE_TEMPLATE.md

Gracias!

**Comment by orlando** [comment]
Cerrando por inactividad.

**Comment by gaboAcosta** [comment]
Te tardas más de un mes en contestar pero en 6 días cierras el issue por inactividad, sounds logic.

**Comment by rbdr** [comment]
@gaboAcosta nada es final don't worry, hay novedades?

**Comment by gaboAcosta** [comment]
La semana pasada tuve release de una app que hemos estado trabajando un poco más de 10 meses, estaba esperando tomarme el tiempo esta semana de llenar el formato que piden, a más tardar el domingo.

**Comment by rbdr** [comment]
Coolness, \m/ la próxima semana vemos que show.

**Comment by orlando** [comment]
@gaboAcosta La idea es que voy a estar revisando esto cada día, si hay interés en dar la platica pueden reabrir el mismo issue comentando. Es mas fácil pasar por 2, 3 issues que pasar por 10+.

**Comment by rbdr** [comment]
@gaboAcosta hay update aquí?

**Comment by gaboAcosta** [comment]
Una disculpa, había perdido de vista esto, pero aquí tengo una propuesta utilizando el template que solicitaron, la idea es una plática para entusiastas de JS que aún no han dado el paso para realizar aplicaciones con Node por falta de herramientas para hacerlo.

# Aplicaciones Fullstack 100% JS en menos de 20 minutos

Se pretende presentar a los participantes como a través del manejo de Yeoman + Bower + Grunt/Gulp se puede tener la base de un proyecto que maneje el stack MEAN, la intención es proveer de una herramienta con la cual de manera rápida y sencilla aquellas personas interesadas en incursionar en desarrollo con NodeJS principalmente puedan crear aplicaciones que les sirvan para estudiar más del tema.

## Background

A lo largo de tres años he desarrollado múltiples aplicaciones en el stack MEAN utilizando scaffoldings para simplificar el desarrollo de las mismas así como aplicaciones sin los mismos. Actualmente soy líder técnico de tres proyectos que involucran estos componentes

## Agenda

1. Herramientas utilizadas en esta plática
  * Grunt/Gulp
  * Bower
  * npm
  * MongoDB
  * livereload
  * socket.io
  * mongoose
  * sequelizeJS
  * AngularJS
  * ExpressJS
  * Yeoman

2. Instalación de dependencias
3. Estructura del proyecto
4. Análisis del código de prueba incluido en el scaffolding
5. Ejemplo de CRUD con el scaffolding
  * Backend
  * Front End
  * Unit Tests

## Take Away

Los participantes serán capaces de crear aplicaciones con el stack MEAN para continuar estudiando al respecto.

## Demo

El demo contará con las siguientes funcionalidades
  * Sección pública
  * Sección restringida con login
  * Creación de documentos con MongoDB sincronizados a través de socket.io (ya incluido con el scaffolding)
  * CRUD completo realizado con sequelize para demostrar el uso de bases de datos SQL en NodeJS

**Comment by rbdr** [comment]
Hmm viendo esta plática me gustaría ver que tanto se pasará viendo código vs explicando como cada una de esas herramientas resuelven un problema. No queremos que las pláticas duren mucho en código o siendo un tutorial, y que expliquen más como algo nos puede resolver un problema.

**Comment by gaboAcosta** [comment]
"No queremos que las pláticas duren mucho en código" - Comunidad de lenguaje de programación, ahora si lo he visto todo, saben que, no hay bronca ya no quiero dar la plática se pasan de posers.

**Comment by rbdr** [comment]
Creo que el código es solo una pequeña parte de la comunidad y como comunidad podemos hacer cosas más interesantes enfocandonos en como resolver problemas que en leer sheets de código que no vamos a recordar o internalizar hasta que sepamos que queremos solucionar. Esta plática también se puede enfocar en eso, en como un stack MEAN puede ayudarnos a resolver esos problemas (El demo es donde pones código, es algo que se pueden llevar a la casa a experimentar directo con el código, por eso lo requerimos, entender código toma más de 20m) pero si realmente crees que es "poser" tratar de enfocarlo de esa manera y no estás dispuesto a adaptar la plática, pues ni modo, no es la plática para esta comunidad.

**Comment by daniel-z** [comment]
Rayos! Quizas no es de mi incumbencia pero cada mensaje de @gaboAcosta suena agresivo. Creo que uno debe esforzarse por tener una buena actitud sobre todo al colaborar con una comunidad. Porque en una comunidad esperas exactamente lo que aquí pasó, simple diferencia de opiniones, la gente no siempre va a estar de acuerdo contigo y no por eso uno debe ponerse así. Además todas las buenas comunidades deben ser regidas por reglas o standards. Bienvenido a las comunidades.

**Comment by gaboAcosta** [comment]
Claro, totalmente de acuerdo con las reglas, pero si te fijas en el historial, se manda un request más de quince días despues se inventa una regla (llenar el formato), se pasa un día de que piden el formato cierran el PR, se hace ver el tiempo, se reabre el issue, se manda el formato, pasa un mes se inventa otra regla (que tal vez es mucho código) ¿cuál comunidad? aquí solo hay dos personas inventando pretextos.

**Comment by rbdr** [comment]
La verdad disculpa por tardarnos tanto, está cabrón manejar todo como voluntarios. Reabrimos el PR porque vimos que se cerró erroneamente. Pero la regla de que es demasiado código no es una regla inventada, es una de las bases con las que formamos la comunidad, de hecho puedes verlo tu mismo en la primera edición del README que está en github desde agosto:

https://github.com/gdljs/gdljs/commit/740bd2bf7d73a359710491b8ec9e24d9fa25fec1

>La plática tiene que ser de 20 minutos máximo. Sabemos que este no es suficiente tiempo para profundizar en el tema, y por eso tratamos de que el contenido de la plática no se vaya muy profundo en el código: con algunos ejemplos es suficiente, por eso pedimos que todas las pláticas vengan con un **demo** que los demás puedan ver en su tiempo si desean profundizar en el tema o reforzar lo que explicaste.

No hay dos personas inventando pretextos, estamos tratando de ayudar a que sea una plática que entre en el marco del evento. Y cualquier discusión al respecto puedes hacerla en el canal `#meta` de nuestro slack (si no tienes cuenta puedes hacerla en http://slack.gdljs.com).

No te lo tomes personal, todos cometemos errores y cuando los hubo los corregimos, no pedimos menos de otros miembros.

**Comment by gaboAcosta** [comment]
Ok, ustedes saben perfectamente cómo llevar su comunidad, estoy seguro que tienen un éxito rotundo y por eso tienen las reglas que tienen, y la verdad es que no es nada personal pero el proceso para interactuar con ustedes ha sido increiblemente frustrante y por eso el tono que alguien por ahí pueda ver como agresivo. En fin, espero que todas sus reglas les ayuden a tener la comunidad perfecta. Saludos.

**Comment by rbdr** [comment]
Gracias por tus comentarios. Salu2

**Comment by Ivanknmk** [comment]
Amigos... ya llene todos sus comentarios como corazoncitos para demostrar que lo único que necesita este mundo es amor y corazones rojos. Los adoro.

**Comment by orlando** [comment]
@gaboAcosta Gracias!, esta cool que la gente aprecie el tiempo que se le dedica a esto. Salu2
