### ISSUE TITLE
Agile Gamification

### ISSUE THREAD

**Issue by chukitow** [gdljs/gdljs#15]
# AgileGamification

Esta es una presentación de un trabajo de investigación que realicé donde analizaba los problemas que se pueden presentar cuando se empieza a adoptar la metodología de SCRUM y como es que se puede mejorar a travez de un una aplicación que desarrolle que usa gamifiación, es decir, introduce las mecánicas de los juegos como puntos, medallas, leader boards y el desarrollo de una one single page app(Rails & AngularJS) que pretende ser similar a Pivotal Tracker que me me ayudaría a implementar gamificación en scrum.

## Background

Este fue mi tema de tesis durante la universidad, estuve investigando mucho acerca de la gamificación y la creación de software gamificado durante mas de 1 año

## Agenda

El contenido de la platica, puedes hacerlo algo así como un indice.

Ejemplo:

1. Introducción
  * Agile
  * Gamificación
2. Gamificación
  * Qué es?
  * Ejemplos
3. Scrum
   * Qué es?
  * Problemas
4. AgileGamification
  * Qué es?
  * Gamificando scrum.
  * Criticas
  * Marco teorico.
  * Herramientas

## Take Away

Los asistentes a travez de esta charla conocerán el concepto de gamifiacación y como lo pueden aplicar en sus proyectos.

## Demo

El demo tiene la funcionalidad de crear un nuevo proyecto, agregar tareas, priorizar tareas, categorizar tareas, estimar tareas, manejar el ciclo de vida de las tareas(iniciarlas, terminarlas, aceptar o rechazarlas), sistema de puntos.

**Comment by orlando** [comment]
Hey @chukitow,

Si puedes responder unas preguntas sobre la platica, hoy agregamos un template que puedes usar para expandir un poco mas el tema y como vas a hablar de el, por favor cambia este issue para que siga ese formato https://github.com/gdljs/gdljs/blob/master/ISSUE_TEMPLATE.md

**Comment by orlando** [comment]
Cerrando por inactividad, cualquier cosa abre el issue nuevamente

**Comment by orlando** [comment]
@chukitow si puedes ponerle un milestone (no se si puedes ponerle un milestone de hecho) tipo para cuando puedes dar esta platica estaría cool

**Comment by chukitow** [comment]
Pues si se puede me gustaría darla en la próxima sesión que seria a final de este mes cierto?

**Comment by rbdr** [comment]
Se me hace chida la idea, me gusta para la de mayo. Me gustaría saber más sobre el demo, como en cómo manejarías ese ciclo, está interesante.

**Comment by chukitow** [comment]
El demo es una herramienta similar a pivotal tracker/jira/trello, básicamente lo que haría será crear un nuevo proyecto, a ese proyecto le agregare una user story, le pondré una puntuación, la categorizaré(feature, bug, chore), una vez creada aparece disponible para comenzarla, después terminarla para revisión, después se acepta o se rechaza, si se aceptó como desarrollador obtengo puntos( como en los videojuegos). Este es el funcionamiento que llegue a desarrollar :)

**Comment by rbdr** [comment]
Noice. Me gusta.
