### ISSUE TITLE
Why doing monkey work if a bot can do it for you?

### ISSUE THREAD

**Issue by lordzero0000** [gdljs/gdljs#16]
# Why doing monkey work if a bot can do it for you?

La charla trataría sobre hubot y como puede ayudarnos a hacer la "talacha" mientras nos enfocamos en cosas que en verdad importan.

## ¿Qué veremos?

1. Sistemas de colaboración
  * Para que sirve y que podemos hacer con ellos.
  * ¿Slack? ¿IRC? ¿Hipchat? ¿Otros?
2. Hubot
  * A brief history of hubot.
  * Para que sirve y que podemos hacer con él.
3. Scripts
  * Como creamos un script.
  * Deja que el bot haga cosas por ti.
  * API.
4. Demo
5. Q & A

## Take Away

Veremos como utilizar un bot para que haga tareas repetitivas por ti. Así de como puede ayudarnos a automatizar varios procesos de nuestro día a día.

## Demo

Levantaremos un bot y haremos que haga algunas cosas por nosotros.

**Comment by orlando** [comment]
Hey @lordzero0000,

Hoy agregamos un template que puedes usar para expandir un poco mas el tema y como vas a hablar de el, por favor cambia este issue para que siga ese formato https://github.com/gdljs/gdljs/blob/master/ISSUE_TEMPLATE.md

Gracias!

**Comment by lordzero0000** [comment]
@orlando done!

**Comment by orlando** [comment]
@lordzero0000 Cool, esto se ve bien!, estas disponible para prepararla para la siguiente reunion? (es el 29 de marzo). Si es asi te scheduleo

Gracias!

**Comment by lordzero0000** [comment]
@orlando Yo digo que sí puedo prepararla para la siguiente reunión.

**Comment by orlando** [comment]
@lordzero0000 Cool, voy a programarte para la siguiente platica, necesitamos tener el contenido para tops el otro lunes

Si puedes mandarme el titulo y el brief de la platica para ponerlo en la pagina estaria tremendo. Saludos!

**Comment by lordzero0000** [comment]
@orlando Genial!

El titulo sería: Let the bot do that for you.
Brief: como utilizar un robot para hacer la "talacha" mientras nos enfocamos en cosas que en verdad importan.

**Comment by orlando** [comment]
@lordzero0000 Tienes el contenido listo?. Puedes mandarlo (slides/demo) para final del día?. Gracias!

**Comment by orlando** [comment]
@lordzero0000 como va el contenido?

**Comment by lordzero0000** [comment]
@orlando tengo el demo de lo que voy a hacer aquí: https://github.com/lordzero0000/nerfbot
En cuanto tenga las slides listas te las mando.

**Comment by rbdr** [comment]
👏👏👏👏👏👏👏👏👏👏👏
