### ISSUE TITLE
 "Testabilidad" en Javascript: Problemas e intentos fallidos de soluciones.

### ISSUE THREAD

**Issue by codingpains** [gdljs/gdljs#17]
# "Testabilidad" en Javascript: Problemas e intentos fallidos de soluciones.

Se presentan ciertos problemas que VoxFeed ha encontrado en el camino a un mejor test coverage, las soluciones que hemos intentando y como han fallado hasta hoy. Presentaremos el proyecto que lleva como "code name" TurboDB y una librería cuyo proposito es dar soporte a MongoDB 100% en memoria.

## Background

Hace casi un año en VoxFeed comenzamos a pensar en mejorar la arquitectura de nuestra plataforma. Parte importante de esta mejora era poder tener mejor cobertura de tests automatizados, de forma que comenzamos a ser muy exigentes en este aspecto y agregamos muchas pruebas unitarias, pruebas específicas en la capa de base de datos y por último pruebas de integración para ejecutar flujos completos.

Al principio todo fué belleza en primavera, pero con el tiempo nos fuimos enfrentando a problemas, por ejemplo que teníamos que hacer una base de datos mock para las pruebas unitarias y las formas de agregarlas era usando inyección de dependencias para lo que usamos proxyquire.

Esto terminó ocasionando dos problemas, en primer lugar Proxyquire se meté con los contextos de javascript y si no tienes mucho cuidado termina contaminandolos mucho al grado que algunas pruebas podrían fallar de formas totalmente aleatorias. Y por otro lado nuestra implementación de base de datos en memoria para no correr pruebas unitarias directo en Mongo nos ocasionó retrabajo. Cada método que ibamos agregando en la abstracción de base de datos teníamos que escribirlo doble, una vez en la base de datos de memoria y una vez en la de mongo. Esto muy pronto nos cansó y nos generó errores cuando olvidabamos agregar un método en la versión de Mongo.

Pronto se nos ocurrió una idea de cómo resolverlo, usando sólo una abstracción de base de datos e inyectando un driver que soportara el api de mongo pero que corriera en memoria.

## Agenda

1. Pruebas automatizadas
  * Qué opinan los grandes veteranos al respecto.
  * ¿Son realmente necesarias?
  * ¿Pueden reemplazarse por otra cosa?
2. Mejorar el tiempo de ejecución
  * Las pruebas son para correrse con mucha frecuencia.
  * Dos Abstracciones, buena idea o mala idea.
3. TurboDB
  * ¿Qué problema intentamos resolver?
  * Suposiciones que se hicieron y resultaron falsas.
  * Complicaciones y resultado final.
4. Nuevas ideas y conclusión.
5. QA

## Take Away

Para empezar me gustaría compartir mis opiniones sobre dos mecanismos que intentan garantizar la calidad de código y dar ejemplos de quiénes los usan y con qué resultados, uno de ellos con pruebas automatizadas y el otro sin pruebas.

Posteriormente sería meternos de lleno al tema de las pruebas y dejar sobre la mesa un par de problemas con los que nos enfrentamos al usar Javascript en proyectos complejos.

Presentar una posible solución que sigue incompleta, pero que es open source y cualquiera puede ayudar a que funcione.

## Demo

TODO.
Me gustaría presentar un demo donde se corran algunas pruebas de un sistema usando acceso a base de datos, otras usando una abstracción repetida y por ultimo donde se sustiya sólo el driver por medio de una inyección de dependencias que no sea obtrusiva.

**Comment by orlando** [comment]
:+1: vamos a schedulear esta para la siguiente reunion ya que @machinesareus tuvo que cancelar

**Comment by MachinesAreUs** [comment]
Una disculpa de nuevo 😓
Espero esto sirva de contexto
https://www.toptal.com/javascript/writing-testable-code-in-javascript
On Monday, March 21, 2016, Orlando Del Aguila <notifications@github.com>
wrote:

> [image: :+1:] vamos a schedulear esta para la siguiente reunion ya que
> @machinesareus <https://github.com/machinesareus> tuvo que cancelar
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/gdljs/gdljs/issues/17#issuecomment-199398448>
>


-- 
"The opposite of a true statement is a false statement, but the opposite of
a profound truth is usually another profound truth."
Neils Bohr (1885 - 1962)

**Comment by orlando** [comment]
Closing, gracias por el talk @con
