### ISSUE TITLE
Desarrollo de aplicaciones nativas con React Native

### ISSUE THREAD

**Issue by charliesbox** [gdljs/gdljs#18]
## Desarrollo de aplicaciones nativas con React Native 

React Native es una nueva tecnología desarrollada por facebook para desarrollar aplicaciones móviles a través de javascript. La palabra clave es "nativo". A diferencia de otras opciones como phonegap o ionic, React Native no usa un webview embebido. Los componentes desarrollados son reflejados como elementos nativos de Android y iOS.

Este es el mejor momento para comenzar a ser desarrollador móvil, reusando gran parte de los conocimientos como web developer.

## Background

Soy web developer en Gbox (una plataforma de distribución de video con base en Mountain View, California). Ahí comencé a trabajar con esta tecnología en un prototipo de lo que sería nuestra aplicación móvil, y actualmente, desarrollando una nueva app cuyo enfoque principal son animaciones que mantengan 60FPS a través de esta tecnología.

## Agenda

1. React Native
  * Qué es? 
  * Porque usarlo?
  * Que pasa tras bambalinas
2. Desarrollo web y desarrollo móvil
  * Comparación del workflow entre ambos ambientes
  * Reuso de lógica entre el mundo móvil y web
  * Integración con apps existentes
3. Antes y ahora: Phonegap y React Native
  * Cual es la diferencia entre ambas opciones
  * Comparación entre React Web y React Native
  * Como y porque se uso en proyectos profesionales
4. Demo
5. QA

## Take Away

Los asistentes tendrán un overview de React Native, y podrán visualizar como este framework ha crecido de forma acelerada en poco más de un  año.

Podrán conocer buenas prácticas, y aprenderán las opciones que hay para comenzar a usarlo, ya sea desde comenzar un proyecto nuevo, o como integrarlo con proyectos nativos existentes.

## Demo

El demo sería una aplicación multiplataforma (android - ios ) que hace uso de la api de Github para mostrar datos de usuarios. El enfoque principal es mostrar los polyfills de React Native, las apis multiplataforma y las apis únicas, y la estructuración de componentes.

**Comment by orlando** [comment]
Esto se ve bastante bien, gracias @charliesbox. Vamos a revisarla para ver cuando la podemos agendar.

Cuando puedes dar esta platica?

**Comment by charliesbox** [comment]
@orlando Podría darla para el evento de este mismo mes, no tengo ningún problema!

**Comment by rbdr** [comment]
@charliesbox ya estás! Te apuntamos, es en una semana el 26 de Abril. Ahorita sacamos los flyers :3

**Comment by charliesbox** [comment]
@rbdr excelente! :D

**Comment by antoinerousseau** [comment]
Chido! Voy a estar ahí! Gracias @charliesbox :)
Vas a hacerlo en inglés o español?

**Comment by charliesbox** [comment]
gracias @antoineroussea! será en español :)
