### ISSUE TITLE
Por que hicimos nuestro propio NodeJS framework.

### ISSUE THREAD

**Issue by sgarza** [gdljs/gdljs#19]
# Por que hicimos nuestro propio NodeJS framework.

En esta platica voy a hablar de por que decidí hacer nuestro propio framework para nodejs, cual es su objetivo, las ideas que tuvimos al evaluar otros frameworks, y por que deberías de considerar hacer lo mismo.

## Background

Aunque el objetivo del framework nunca ha sido tratar de resolver todo, hay cosas que se pueden mejorar o simplificar, si nos sirve a nosotros seguro que le puede servir a alguien mas.

## Agenda

1. Intro
  * Quienes somos
  * Nuestra experiencia
2. Por que necesitamos un framework?
  * Características que buscamos.
  * Soluciones existentes.
  * Evaluación y experiencia
3. Que es un framework?
  * Podemos construir uno?
  * Primeras experiencias
  * De la teoría a producción
4. Feature-set
5. Demo
6. QA

## Take Away

Una nueva herramienta que, como a nuestro equipo de trabajo, te puede ayudar a construir applicaciónes de una forma mas ordenada.

## Demo

**TodoMVC+**
* Por que es el defacto para mostrar frameworks
* `+` Con multi-usuario para hacerlo mas interesante
* Persiténte en postgres

**Comment by rbdr** [comment]
Looks good. Que te parece para S02E01 en mayo

**Comment by sgarza** [comment]
Yep :)
