### ISSUE TITLE
Real Time Communications with WebRTC

### ISSUE THREAD

**Issue by ulifigueroa** [gdljs/gdljs#2]
## Abstract
WebRTC es una tecnología que permite realizar comunicaciones en tiempo real utilizando un navegador web. En esta plática aprenderemos los conceptos básicos y las partes que la conforman e implementaremos unos ejemplos para entender como podemos construir aplicaciones utilizándola.

## Agenda
- Introducción a WebRTC
- La motivación detrás de esta tecnología
- Como funciona?
- API
- Demo

## Demo
Un conference room simple utilizando WebRTC

**Comment by rbdr** [comment]
Me gusta, se que hay mucho que se puede de explorar de WebRTC, pero no hace mucho @albertein se aventó una plática de real time collaborative apps en las que enseño un demo de WebRTC (Slides: https://speakerdeck.com/gdljs/real-time-collaborative-apps-with-js-by-at-albertein ; Video: https://www.youtube.com/channel/UCzxbJ7cm2Wti_AIUUjwuLGw)

La plática cubrió cosas aparte de WebRTC, pero el demo tenía data y video por red. Tal vez estaría bueno ver como podríamos distinguirlas para profundizar un poco sobre lo que ya hizo Alberto como un "Next Steps" tomando donde dejó?

No se que les parezca.

**Comment by ulifigueroa** [comment]
Ya veo, lo que se me ocurre es enfocarla únicamente en WebRTC y abundar en el tema, hablar a detalle sobre ICE protocol, SDP, las diferencias entre las implementaciones de WebRTC en los navegadores y la adopción actualmente. O incluso podría hablar sobre la experiencia en WePow al implementar esta tecnología en nuestro producto Live http://www.wepow.com/live; los problemas que hemos tenido en conexiones restrictivas en enterprise, problemas en producción y la adopción.

**Comment by albertein** [comment]
:+1:  en ahondar en los real wolrd pains de hacer un deployment publico, si es para octubre algo así como, Taking WebRTC to production, a horror show

**Comment by rbdr** [comment]
Nice! Me gusta eso último, entrar sobre cuales son los gotchas de WebRTC en un ambiente de producción. No solo ver que esos protocolos están ahí, pero también demo de como una de esas tecnologías puede evitar pedos reales.

**Comment by ulifigueroa** [comment]
Perfecto voy a cambiar el titulo y la definición sobre esa linea para comenzar a trabajarlo.

**Comment by orlando** [comment]
Con los cambios sugeridos, creo que sería tremenda platica. So por mi 👍🏿

**Comment by orlando** [comment]
@ulifigueroa any news about this?

**Comment by orlando** [comment]
Closing this
