### ISSUE TITLE
Manejando programadores

### ISSUE THREAD

**Issue by richistron** [gdljs/gdljs#20]
# Manejando programadores

Está es un charla donde vamos a tocar temas de los que casi nunca se habla. Scrum es uno de los procesos más famosos para el desarrollo de software, pero hay ciertas cosas que no dicen, como el hecho de que estamos quemando developers y los hacemos trabajar los fines de semana y por las noches. Cuando el management funciona esto no debe pasar; sin embargo, vemos esto todos los días con la fechas de entrega limitadas y los requerimientos que cambian cada sprint.

## Background

Tengo más de 6 años de experiencia trabajando para empresas internacionales y he visto en carne propia como un mal manejo puede llevar al fracaso de un proyecto y perdidas millonarias.

## Agenda

- Productividad 130%. Les voy a platicar la historia de un project manager que logró incrementar su productividad como nunca nadie lo había logrado.
- Vamos a platicar acerca de los diferentes tipos de programadores.
- Mencionaremos las peores prácticas de scrum.
- Vamos a tener memes.

## Take Away

Los asistentes aprenderán un par de tips para darse cuenta de cuando al proyecto se lo está cargando el payaso 
![img](https://i.ytimg.com/vi/IbD0k13S4RY/maxresdefault.jpg) 

## Demo

Está es un plática basada en experiencias personales y esta charla https://www.youtube.com/watch?v=NPlMcUxFOlY (el audio es muy malo)

**Comment by escusado** [comment]
Me gusta que no sea "código", lo cual hace dificil hacer un "demo" para esta, pero que tal algún ejercicio sencillo de como hacer scrum de un "TODO list" o algo así? o cómo planeas mostrar el proceso?

**Comment by rbdr** [comment]
@richistron algún update respecto a lo del demo?

**Comment by richistron** [comment]
no voy a hacer demo, mejor cerramos este issue

**Comment by rbdr** [comment]
oh wow ok
