### ISSUE TITLE
Concurrencia, paralelismo y el event-loop

### ISSUE THREAD

**Issue by orlando** [gdljs/gdljs#21]
# Concurrencia, paralelismo y el event-loop

Concurrencia y paralelismo son temas que siempre generan un poco de confusión, y también está esa bestia rara que es el event-loop. Voy a hablar un poco de como funciona y dar algunos ejemplos de como se comporta Node.js vs otro lenguaje como Go.

La platica va a ser en Español

## Background

He estado trabajando por los últimos 2 meses con Go, al ver que Go tiene paralelismo built-in en el lenguaje, hice un poco de research de como Node.js maneja esa parte.

## Agenda

1. Concurrencia
  * Que es?
  * Ejemplo
2. Paralelismo
  * Que es?
  * Ejemplo
3. Concurrencia y Paralelismo
  * Diferencias
  * Ejemplo
4. Node.js event-loop
  * Que es?
  * Como se comporta
  * Ejemplo
5. Demo
  * Concurrencia en JavaScript
  * Paralelismo en JavaScript
  * Concurrencia en Go
  * Paralelismo en Go
6. QA

## Take Away

Dejar en claro que son los términos concurrencia y paralelismo, y explicar como trabaja el Event-loop en JavaScript. También como conocer estos conceptos afecta la forma en que programamos.

## Demo

El demo va a mostrar como llenamos un Grid de NxN (en el browser o en la terminal) con colores. Las respuestas se van a generar de maneras distintas para mostrar la diferencia entre concurrencia y paralelismo.

El demo va a cubrir un poco de código en Node.js y Go.

**Comment by escusado** [comment]
Nice! Me gusta que hay Go, seguro a la banda le da curiosidad como se ve

**Comment by orlando** [comment]
Estuvo chida

**Comment by orlando** [comment]
🚀

**Comment by a-rmz** [comment]
@orlando, ¿Me puedes pasar la página que usaste para el demo del event loop en tu presentación?

**Comment by orlando** [comment]
@a-rmz http://latentflip.com/loupe

**Comment by a-rmz** [comment]
Ufff, chido, muchas gracias. 😄

**Comment by damiancipolat** [comment]
Hola me interesa mucho este tema, hay algun lugar que pueda ver la charla que distes o documentos para leerr sobre esto?

**Comment by orlando** [comment]
@damiancipolat http://speakerdeck.com/orlando acá puedes ver los slides y el video https://youtube.com/watch?v=wElQNOGS8-c, en Los slides vienen unos recursos pero si quieres algo en específico puedo extender un poco el tema en un blog post. Que te gustaría ver?

**Comment by orlando** [comment]
Oh por cierto olvide de hacerle fork al demo al repositorio de GDLJS (si alguien con permisos de fork lo puede hacer estaría genial @toily @rbdr) acá está el código por ahora https://github.com/orlando/event-loop-demo

**Comment by damiancipolat** [comment]
@orlando muchas gracias! voy a estar estudiando todo este material que me mandas!

**Comment by orlando** [comment]
@damiancipolat 💪
