### ISSUE TITLE
¿Cómo empezar a programar?

### ISSUE THREAD

**Issue by amicavi** [gdljs/gdljs#22]
# ¿Cómo empezar a programar?

A través de esta plática compartiré mi historia del camino que seguí para comenzar a programar.

## Background

Con apenas 9 meses desde que tomé la decisión de querer aprender a programar y sabiendo que no tenía conocimientos previos, compartiré el proceso que hasta ahora he seguido para impulsar a más personas a vencer el miedo de comenzar algo nuevo.

## Agenda

1. Presentación
   * ¿Por qué quise cambiar mi profesión?
2. Aprendiendo a aprender
   * Selección de Lenguajes
   * Tutoriales
3. Equivocarse
   * Tener un problema
   * Imitación
4. Aprender a pensar en problemas
   * Externalización
   * Proceso de Solución de problemas
5. Journaling
6. ¿Cómo esto ha cambiado mi vida?

## Take Away
Compartir los procesos y herramientas que me han ayudado a aprender, y así impulsar el camino de aquellos que apenas están por tomar esta decisión.

## Demo
Los problemas que he resuelto con externalización y journaling.

**Comment by rbdr** [comment]
Yay!

**Comment by escusado** [comment]
daaaaaaaamn guuuurl lets do this!!! 👍👍👍👍👍👍👍👍  En el demo estaría chido que mostraras como el journaling ayudó en una decisión específica, o como externalizar te aliviano un problema en particular, vaya como el proceso que llevas te ayudo en las particularidades de la bronca.

**Comment by amicavi** [comment]
Me late, si claro! 
Tengo el perfecto demo de externalización y journal, estaría bien mostrar un spec? o solo mencionar por qué me ayudó?

**Comment by rbdr** [comment]
Si tienes el spec y lo puedes attachear al repo estaría 👌

**Comment by NineInchTooL** [comment]
Huuufffff +1 en esta platica

**Comment by amicavi** [comment]
Me da penita mi spec hahaha es de los primeros que hice.

**Comment by orlando** [comment]
Estuvo con madre! 🚀
