### ISSUE TITLE
Caldo de Kafka para Node

### ISSUE THREAD

**Issue by albertein** [gdljs/gdljs#23]
# Caldo de Kafka para Node

En esta charla hablaremos sobre que es Apache Kafka, en que se diferencia de otros queues y use cases comunes.

## Background

En Wizeline usamos Apache Kafka como un componente principal de nuestra arquitectura de backend donde yo he estado involucrado en la implementación y diseño.

## Agenda

1. Intro
2. Components
   + Zookeeper
   + Brokers
   + Producers
   + Consumers
   + Topics
   + Partitions
   + Offsets
3. Design principles
    + How different is from RabbitMQ & Friends?
4. Demo
5. Q & A

## Take Away

Que es Kafka y como puede ser utilizado en tu aplicación e infraestructura. 

## Demo

El demo mostrara una aplicación que produce información para ser procesada en el background por workers.

Los workers consumirán información publicada en Kafka y se demostrara como se pueden hacer escalar sencillamente con solo levantar mas workers.

**Comment by rbdr** [comment]
lol el título, A+++ lo leería de nuevo

**Comment by Ivanknmk** [comment]
Yo voto por esta platica como 20 millones de veces.

**Comment by orlando** [comment]
🚀

**Comment by rbdr** [comment]
Gr8 talk
