### ISSUE TITLE
Que ocupas pa 3D

### ISSUE THREAD

**Issue by escusado** [gdljs/gdljs#24]
# Title

Utilizando < canvas > dedicaré la plática a transmitir un poco de cómo yo entendí el mecanismo para usar el API de 3D

## Background

Me tocó desarrollar un mapa en 3D para el jale y me dí cuenta de varios patrones de diseño interesantes que surgen al codear para el 3d context. Me gustaría compartir los pormenores de mis decisiones y de cómo atacar una primera iteración de un problema que requiera 3d en web.

## Agenda

How 3D got to web
1. history
 * humble beginnings
 * java applets
 * svg
 * flash
 * js happened
 * Vladimir Vukićević at Mozilla
 * canvas
 * webgl & hardware acceleration
2. how does it works
 * <canvas>
 * loop
 * scene & camera
 * rendereables
 * units
3. My problem (demo)
 * Draw an object
 * Create camera job
4. QA

## Take Away

Tendrán una idea básica de que hacer y que buscar cuando quieran hacer webgl based stuff

## Demo

Un pequeño interactivo utilizando 3d y algún tipo básico de input pero sitll TBD

**Comment by salvadorbfm** [comment]
Yo sólo digo que sea:
"Que necesitas pa 3D" ;p

**Comment by rbdr** [comment]
8 Thumbs up, lets do this.

**Comment by rbdr** [comment]
Gr8 talk
