### ISSUE TITLE
Construyendo la mejor experiencia de pagos en línea.

### ISSUE THREAD

**Issue by chukitow** [gdljs/gdljs#25]
# Construyendo la mejor experiencia de pagos en línea.

Es una charla  donde se exponen malas prácticas cuando se implementa un sistema de pagos en línea y como mejorarlos a travez del uso de una buena práctica a la **chuck norris way**

## Background

Recientemente en una "startup" que inicié, nos dimos cuenta que los usuarios no adquirían nuestro producto porque no podían completar el proceso de pago(si funcionaba solo que no entendían paypal haha) así que hice un research exhaustivo de las mejores prácticas.

## Agenda

1. Introducción
  * Quien soy
  * El problema
2. Best practices
  * Mobile-friendly
  * Captchas
  * Mobile input types
  * No Ask for registrations before purchase
  * No auto-detecting credit card type
  * Credit card validation 
4. Demo
5. QA

## Take Away

Los asistentes aprenderán como implementar la mejor experiencia de pagos para que sus clientes les den su dinero sin problemas

![image](https://cloud.githubusercontent.com/assets/4173376/17186402/b2d5357a-53fa-11e6-8cb3-d8533efee054.png)

## Demo

El demo sera una página sencilla donde se muestren estas prácticas en acción

**Comment by rbdr** [comment]
@chukitow u in para agosto
