### ISSUE TITLE
Cuántos UXs tiene mi API

### ISSUE THREAD

**Issue by sirgalleto** [gdljs/gdljs#26]
# Cuántos UXs tiene mi API

Es una charla para hablar de malas experiencias trabajando con APIs hechas y cómo mejorar estas experiencias con buenas prácticas. 

## Background

Cuándo haces un API no sólo tienes que preocuparte por exponer unos cuántos servicios, también tienes que utilizar todos tus recursos para que la persona que la consuma tenga la mejor experiencia de usuario y no tenga inconvenientes en el momento de usarla.

## Agenda

1. Introducción
  * Quién soy
  * Qué es un API
2. Malas experiencias
  * Cuándo conocidos enviaban user y pass con una petición GET
  * Cuándo updateCar era un POST 
3. Buenas prácticas
  * Entendiendo *poquito* las peticiones HTTP
  * Códigos de respuesta
  * Entendiendo los errores
4. Demo
5. Preguntas

## Take Away

Si asistes a la plática problablemente te reirás de APIs graciosas y aprenderás a contar cuántos UXs puede tener tu API según las buenas prácticas que uses.

## Demo

El demo puede ser un par de endpoints con varios responses dependiendo de lo enviado.

**Comment by rbdr** [comment]
Estaría interesante en el demo ver diferentes formas que puedes cambiar el """""developer experience""""" para que un API con la misma funcionalidad sea horrible o chidis

**Comment by sirgalleto** [comment]
@rbdr Siento también que podría tener un cliente consumiendo el api y mostrando mensajes de error dependiendo del error del servidor y cómo esto puede también afectar la ux de un site.

**Comment by escusado** [comment]
Yeah! suena chido also simón lo del user experience se me hace interesante, me recordó a este talk igual te ayuda para ideas: https://www.youtube.com/watch?v=qCdpTji8nxo

**Comment by sirgalleto** [comment]
Gracias por la oportunidad. Salu2 💘
