### ISSUE TITLE
Como aprendí a dejar de preocuparme y amar ~~la bomba~~ JS

### ISSUE THREAD

**Issue by arturomc** [gdljs/gdljs#27]
# Como aprendí a dejar de preocuparme y amar ~~la bomba~~ JS

Viniendo de un background de fanatismo Javero en contextos super ~~mamones~~ restringidos, cómo es que el switch de lenguaje fué y es el siguiente paso lógico en tu camino para volverte un awesome ninja dev y la sarta de perks and quirks con los que te encuentras en el mundo prejuicado del desarrollo de software.

## Background

Soy un ex-Javero que vio el camino de la luz y comenzó a interesarse en JS cuando Node estaba naciendo, apoye en el desarrollo de NodeJS (tanto como apoya una cucharada de sal a volver el mar mas salado, pero algo hice :+1: ) y de varios proyectos que en su momento fueron relevantes, mas que nada resolviendo issues o haciendo comentarios sarcásticos sobre ellos (this helps a lot, true story). He trabajado como dev de JavaScript desde hace 4 años ( por que hacer botones y paginas web no cuenta al parecer ) y tengo un bizarre love triangle con react y angular.

## Agenda

1. Cambios extraños que hay en mi
  * Por que el switch de lenguaje 
  * Con lo que te encuentras al entrar al mundo de JS desde otro lenguaje
2. The good parts
  * Cuando te das cuenta que vas por buen camino 
  * Cuando te das cuenta que en realidad ese commit no debia ver la luz del día
  * Cuando comienzas a entenderlo todo 
3. Experiencia, seniority y otras mentiras
  * El novedoso sistema de seniority del siglo XIX
  * Cambiando la cultura
  * Y ahora solo queda mejorar hasta morir
4. Moraleja

## Take Away

Quiero compartir mi visión de este tema ~~por que mi madre dice que soy único y especial~~ para los devs de JS y de otros lenguajes que aman a viva voz o en secreto a JS, o tienen casos de sindrome de impostor al llevar un rato en JS sin dirección o guidance, quiero que sepan que mientras vayan, van bien, y siempre pueden ir mejor.

## Demo

No requiere demo, pero he aqui [una demostración de lo que pasa cuando mezclas agua y poliaclirato de sodio 
](https://img.buzzfeed.com/buzzfeed-static/static/2014-07/31/11/tmp/webdr07/anigif_f05904977cbe90132ecd5fea9bc858c7-15.gif?no-auto)

**Comment by rbdr** [comment]
Aunque no require demo, crees que haya algo que se pueda hacer como un repo que de alguna forma refuerze estas ideas? ... Se que está medio ambiguo por la naturaleza de la plática pero estaría interesante si podemos hacer algo por ese lado imo

**Comment by joseluistorres** [comment]
Perdon que me meta @rbdr una comparacion de una app de J2EE o con JBoss comparada con una de NodeJS, filosofia, o estructura? O tal vez una comparacion de como se implementa un controller, tal vez estoy sobre pensandolo... 😊

**Comment by rbdr** [comment]
@joseluistorres al contrario, pusimos la integración en slack para que haya más discusión y fiesta. Estoy seguro que hay partes donde es muy clara la diferencia de filosofía, y puede ser un eye opener, tmb para gente que está en tu mismo caso pero apenas haciendo el switch

**Comment by escusado** [comment]
Me encanta el tema, y si creo que a manera de demo, un benchmark de complexity entre Java y Js a ver cual es más simple, rápido. Digamos un api simple que haga un `echo` o micro `todo`. O quizás 2 diagrams denotando la arquitectura de un mismo componente a ver como se ve en los 2. O quizás una comparativa de tu código antiguo de Java vs algún script nuevo que puedas mostrar para contrastar ese show? Pero A+++ con el tema!

**Comment by arturomc** [comment]
Me late, me late, una comparativa de filosofías y workflows, quiero evitar comparar como hacer cosas especificas, pero me late lo de una app en J2EE vs una de NodeJS, o comparar APIs, le dare vueltas hoy en la noche para regresar con algo interesante como demo, thanks for the feedback!

**Comment by nicandromts** [comment]
disculpa @arturomc has usado Adobe Experinc Manager? y si no es el caso, que opinas de los large-scale CMS's que usan J2EE?

**Comment by nicandromts** [comment]
a mi me ha costado muchisimo aprenderlo

**Comment by arturomc** [comment]
@Nicando trayendo su hate por el ECM de Adobe a este foro xD

No he tenido el gusto de conocer AEM "intimamente", pero para CMSs, enterprise o no, creo que Java is too much, [quoting Joe Armstrong](http://www.defprogramming.com/quotes-by/joe-armstrong/) quieres una banana pero terminas con el gorila y toda una selva.

J2EE, por otro lado, como vivimos en una era hermosa de SOA, microservicios y pokemongo, puede construir interfaces hermosas, seguras y faciles de consumir, siempre y cuando la meta sea hacerlas hermosas, seguras y faciles de consumir, which seldom happens, en teoría debería ser transparente consumir o, en menor grado, mantener/escalar un CMS que usa J2EE.

Para terminar, recordemos la ley de Atwood: any application that can be written in JavaScript, will eventually be written in JavaScript. (agregando referencia a JavaScript para que el moderador no cierre mi ticket por ser offtopic)

**Comment by rbdr** [comment]
@nicandromts por favor mantenlo on-topic. Este lugar es para discutir la plática. Para chat general está el slack.
