### ISSUE TITLE
Platica: booljs del desarrollo a la comunidad. 

### ISSUE THREAD

**Issue by svzosorio** [gdljs/gdljs#3]
Como les platiqué en el otro GDLJS, hace un tiempo trabajamos en el proyecto de [booljs](http://booljs.co), quisiera comentarles bien de qué se trata el proyecto y hacer un demo para demostrar cómo funciona.

**Comment by orlando** [comment]
@svzosorio Esto esta chido, que quieres hablar específicamente?

**Comment by svzosorio** [comment]
@orlando Comentarles algo de como comenzó, cómo funciona y algún ejemplo.

**Comment by rbdr** [comment]
@svzosorio como sería del demo de booljs?

**Comment by rbdr** [comment]
@svzosorio scheduled for november

**Comment by orlando** [comment]
@svzosorio we need to see something tops Nov 21. La reunión es el 24

**Comment by orlando** [comment]
Closing
