### ISSUE TITLE
Google spreadsheets _The ultimate database_ - (O tabletop.js un caso de uso)

### ISSUE THREAD

**Issue by regenhans** [gdljs/gdljs#30]
# Google spreadsheets _The ultimate database_ - (O [tabletop.js](https://github.com/jsoma/tabletop) un caso de uso)

La historia del cómo un proyecto colaborativo me hizo aprender e implementar una nueva tecnología en un par de días para crear una plataforma  de transparencia open source y un pequeño caos político (... mientras mi vesícula explotaba).  
## Background

Soy un apasionado del JS. Wanabbe de software engineer y diseñador estratégico. Le muevo a las relaciones humanas y al bash.

Me pareció un caso de uso curioso y me gustaría compartirlo.
## Agenda
1. Los requerimientos del proyecto en que le me metí
   -  Contexto sobre tecnología cívica
   -  La misión de #informebajolupa
   -  El reto de crear una plataforma de transparencia en 1 día
2. La herramienta que decidí usar ([Tabletop.js](https://github.com/jsoma/tabletop))
   - Qué es 
   - ¿Cómo funciona?
   -  [DEMO]
3. Aprendizaje
   - ¿Por qué quieres usarlo en un proyecto?
   - ¿Por qué NO quieres usarlo en un proyecto?
   - ¿Por qué es bueno participar en proyectos de este tipo? 
4. Otras curiosidades de la plataforma
   - UX testing en 3 horas
   - Google cloud it's pretty awesome
     - Aunque me genere dockerfiles de la nada
   - El impacto de proyectos "pequeños"
5. QA
## Take Away

Aprenderán sobre la existencia de una librería muy útil para ciertos casos y nada útil para la mayoría de las cosas. Veremos un poco del proceso de planeación del proyecto, por qué se usó esta librería y qué me hubiera gustado saber antes de usarla.
## Demo

[Código en el repo](https://github.com/regenhans/informebajolupa)

[PLATAFORMA](http://informebajolupa.mx)

**Comment by escusado** [comment]
Love it! Me gustaría saber en que otros proyectos está jalando `tabletop.js` y que otras alternativas parecidas existen :) 👍

**Comment by pekosoG** [comment]
Orale, suena interesante, podría ser de ayuda para proyectos en puerta
