### ISSUE TITLE
Creando la nueva generación de nuestro player con React Native

### ISSUE THREAD

**Issue by rcvrgs** [gdljs/gdljs#31]
# Creando la nueva generación de nuestro player con React Native

En Ooyala, creamos la nueva generación de nuestro video player usando React Native. Por qué? Fue fácil integrar el bus de datos que manejamos en el player para poder agregar nuevas funcionalidades (plugins) a lo que ya teníamos y de paso crear una nueva interfaz que los usuarios disfruten. Con React Native pudimos desarrollar el player para iOS y Android en aproximadamente 6 meses.
## Background

Empecé a trabajar cuando el proyecto comenzó a desarrollarse. Personalmente, no estaba convencido de usar frameworks multiplataforma (como Phonegap, react native, etc) ya que yo soy un desarrollador de apps móviles nativas de Android y iOS, pero al usar React Native me di cuenta de lo limpio y claro que es. Ahora es parte integral de nuestra nueva plataforma de video, y lo mejor es que nuestro proyecto es open source. Así que quiero compartirlo para que conozcan la experiencia que tuvimos en Ooyala y que lo prueben ustedes mismos.
## Agenda
1. Player v3
   - Arquitectura del player v3.
   - Interfaz de usuario.
2. Retos de player v3
   - Difícil de personalizar.
   - Difícil de incorporar plugins por third parties.
3. Player v4 
   - Incorporación de react native y por qué?
   - Arquitectura del player v4.
   - Integración de plugins a player v4.
   - Nuevos retos que enfrentamos.
4. Extender React Native
   - Creación de componentes reusables y compartir a la comunidad
5. Demo
6. QA 
## Take Away

Cómo funciona React Native en un proyecto usado por clientes de Ooyala a nivel mundial, y cómo contribuir a proyectos open source que usan react native.
## Demo

Probablemente haga un fork del repositiorio de nuestro player (https://github.com/ooyala/native-skin), y el demo puede consistir de crear un componente nuevo en la plataforma.

**Comment by escusado** [comment]
Sounds great! :D 👍

**Comment by sirgalleto** [comment]
Siempre he querido saber qué pedo con los players. A huevo.

**Comment by rbdr** [comment]
Me gusta la idea del demo! La plática suena bien. Lo único que me queda duda es sobre que tanto code se va a ver en la parte de arquitectura, la plática es 20m y tratamos de que no haya mucho de código en la presentación y se enfoque más en lo que se resuelve o así y el demo sirve para reforzar esa parte.

**Comment by rcvrgs** [comment]
@rbdr, quiza aqui podemos modificar la platica segun lo que quieran ver. En la parte de la arquitectura solo estoy pensando poner alguna imagen o ejemplo basico de como se diseño el player. Realmente no pienso mostrar código aquí, si no puedo empezar a divagar en código que no van a saber ni qué es. Es sólo para que quede claro que el player v3 no es muy modular.

**Comment by rbdr** [comment]
@rcvrgs aah noice! Suena pefrecto.

**Comment by pekosoG** [comment]
me late un chingo 👍
