### ISSUE TITLE
Propuesta: js design patterns

### ISSUE THREAD

**Issue by sirgalleto** [gdljs/gdljs#32]
Últimamente he leido sobre patrones de diseño en js y se me hace muy intersante aprender y enseñar a utilizarlos como un pilar de JavaScript, sin embargo pese a que son muy importantes  son bastantes patrones como para abordarlos en más de una plática mensual regular, entonces he estado pensando si podríamos abrir unas pláticas de estudio en donde varios expositores agarramos un patrón y nos reunimos una vez al mes para hablar de un par de estos patrones junto con su implementación y quizá añadir un demo pequeño o puestas en acción.

Qué les parece?

**Comment by orlando** [comment]
@sirgalleto que onda con esto?, como va/quedo?

**Comment by sirgalleto** [comment]
@orlando quería que en comentarios me dijeran que les parecía. Según se me ocurió serían una serie de pláticas cortas una vez al mes con diferentes expositores hablando del tema. Es un tema de estudio que puede tardarse un par de sesiones y ya.

**Comment by orlando** [comment]
@sirgalleto voy a cerrar esto, el ultimo mensaje fue hace 2 meses. Si quieres puedes seguir la conversacion en slack
