### ISSUE TITLE
Como ser un newbie y no morir en el intento 

### ISSUE THREAD

**Issue by KarlyGrCm** [gdljs/gdljs#34]
# Como ser un newbie y no morir en el intento 

Me gustaría hablarles de mi historia, de mi paso como estudiante y ahora como parte del mundo laboral, mis tips, mi experiencia y la de algunas personas a mi al rededor que iniciamos bajo las mismas circunstancias, que es lo que hace la diferencia. Prácticamente como pase de ser estudiante a iniciar la búsqueda por oportunidades.

## Background

Soy recién egresada, y hasta entonces no me di cuenta de la **gran** diferencia entre el mundo real y mi vida en la escuela, mi acercamiento a las comunidades y a personas con ganas de entrenar e inspirar a personas con ganas de aprender.

## Agenda

1. Presentación
  * Poquito sobre mi
2. Cosas que no me dijo nadie en la universidad
  * Expectativa vs realidad
3. Mis primeras comunidades
4. Mentoring
 * Como buscar al mentor ideal

## Take Away

Como se que muchos ya pasaron (o no) por esta bella etapa de estudiantes, lo que quiero compartir mas que nada entrar en un mundo lleno de Devs chidos y como estos fueron parte importante de mi desarrollo tambien, y como ya como un experimentado ayudar a un estudiante a ir por el camino de la luz

## Demo

No es una charla con demo 😞  Igual tal vez cambie algunas cosillas peero, al menos ya la propuse xD

**Comment by orlando** [comment]
@KarlyGrCm Genial, me gusta. Un demo de esto puede ser comparar algo del código que hacías al principio con el que haces ahora, vamos a ver que ideas sacamos, pero overall esta 👍

**Comment by KarlyGrCm** [comment]
@orlando me late, dejame ver que me hayo para poner c:

**Comment by pekosoG** [comment]
@KarlyGrCm me late, también la idea de @orlando suena interesante... ojalá no te de penita enseñar codigo viejo jeje

**Comment by KarlyGrCm** [comment]
@pekosoG para nada! Yo se que nadie nace sabiendo 🤓  lo que si es que no se si aun tenga algo de código viejo

**Comment by orlando** [comment]
@KarlyGrCm @pekosoG yo tengo uno de las primeras cosas que codie haha en github. https://github.com/orlando/aspblOOg. Todavia sigo escribiendo el mismo codigo feo

**Comment by orlando** [comment]
@KarlyGrCm puedes presentar para la siguiente reunion el 29 de Noviembre? (https://github.com/gdljs/gdljs/milestone/11). De ser así para schedulear esta plática

**Comment by KarlyGrCm** [comment]
Claro, sin problema :)

**Comment by orlando** [comment]
@KarlyGrCm cool gracias
