### ISSUE TITLE
Functional Programming in a non Functional World

### ISSUE THREAD

**Issue by AlgusDark** [gdljs/gdljs#35]
# Functional Programming in a non Functional World

La plática se enfocaría en cómo podemos utilizar conceptos básicos de Functional Programming, cómo podemos ejercitar nuestro cerebro para implementar éste paradigma día a día.

## Background

Mi nombre es Carlos Pérez Gutiérrez y soy un backend developer que descubrió javascript gracias al amor de Ruby y los lenguajes dinámicos. Actualmente laboro en EPAM, donde aplico cosas básicas de functional programming con javascript.

## Agenda

1. What is Functional Programming?
* Pure functions
* Immutlable
* Benefits of FP
2. Why JS?
* Functions as First-class citizens
* Closures and scopes
3. Let’s get functional
* Fancy Words
4. Transforming, gathering and removing
5. QA

## Take Away

Los asistentes conocerán los conceptos básicos de FP, sus ventajas y ejemplos prácticos para comenzar a utilizarlos en el día a día.

## Demo

No tengo una demo definida, pensaba en algunos ejercicios sencillos para comenzar a pensar sin loops y utilizar funciones para tareas cotidianas (map/filter/reduce/Object.Assign) así como algunos ejemplos con algunas librerías para mencionar su importancia para aprender Functional Reactive Programming (quizá en un futuro pueda seguir con esa charla).

**Comment by rbdr** [comment]
Hmm, aunque está suave el tema acabamos de tener una plática con este tema

**Comment by orlando** [comment]
Hey @AlgusDark,

Ya este tema lo tuvimos hace unos meses (y tenemos otro issue abierto con el mismo tema), por los momentos nos gustaria ver otra cosa en el meetup. Algo mas que tengas en mente para presentar?

Acá los issues
https://github.com/gdljs/gdljs/issues/13
https://github.com/gdljs/gdljs/issues/28

**Comment by AlgusDark** [comment]
Voy a trabajar en una propuesta de WebRTC, por lo que éste issue pueden cerrarlo, volveré a abrir uno cuando tenga el de WebRTC. Nos vemos el martes.

Saludos.

**Comment by orlando** [comment]
Hey @AlgusDark,

Vamos a necesitar algo para el Viernes, a mas tardar el Lunes, para revisarlo y ver cualquier feedback que podamos darte. Crees que puedas tenerlo para esos dias?

**Comment by AlgusDark** [comment]
Oh, me refería a que lo iba a trabajar para otro meeting, éste se me
complica demasiado por los tiempos :S

El de WebRTC lo trabajaré y abriré un nuevo issue para que lo revisen y ver
si entra en el siguiente.

Muchas gracias.

**Comment by memorammstein** [comment]
Que onda @AlgusDark,

hace ya algún tiempo el buen @albertein se aventó https://speakerdeck.com/gdljs/real-time-collaborative-apps-with-js-by-at-albertein , y, aunque no se trató de webRTC, sí lo tocó, para que lo tomes en cuenta.

**Comment by AlgusDark** [comment]
Gracias por el dato, déjenme ver que puedo ir tramando para no proponer
solo un tema.

Saludos.

**Comment by orlando** [comment]
Hey @AlgusDark, 

la reunion es en 2 semanas, no el siguiente martes. Aun así no tienes chance de preparar algo?

Saludos!

**Comment by AlgusDark** [comment]
Cierto, que tal un tema básico de Rxjs?, puedo armar un esqueleto para que
lo revisen.

**Comment by sirgalleto** [comment]
Apoyo lo de RXJS.

**Comment by orlando** [comment]
Eso suena bien

---Sent from Boxer | http://getboxer.com

**Comment by AlgusDark** [comment]
Ok, déjenme armarlo para dar una charla introductoria del loco mundo de
Reactive Programming.

Pongo el temario en este mismo issue? (con el templete por supuesto) o abro
uno nuevo?

**Comment by orlando** [comment]
Vamos a cerrar este issue y continuamos la conversacion en el nuevo @AlgusDark. Feel free de abrir el otro issue.

Cheers
