### ISSUE TITLE
An Internet that forgets

### ISSUE THREAD

**Issue by rbdr** [gdljs/gdljs#38]
# An Internet that forgets

An exploration of technologies that remove the permanence of content.

## Background

I've been experimenting with doing ephemeral posts and ways of designing a social network to force it to be temporal. We'll talk a bit of why it sucks that everything is permanent, and why it doesn't have to be that way, also: technology to help us get there.

## Agenda

(Not final, at all, but pretty much)

1. Demo
2. Everything is Permanent: Everything Sucks
3. The Joy of Ephemera
5. Social Responsibility and Us

## Take Away

I want to talk about ephemeral technology but focus on social responsibility when building apps: Our tools can be dangerous even if we don't intend to.

## Demo

A small social network that forgets depending on the conversation length.

**Comment by escusado** [comment]
Me gusta, suena a que vas a tratar el tema del lado cultural más que tecnológico cierto?
Estaría chido saber de casos/productos donde el ángulo efimero no pegó.

**Comment by rbdr** [comment]
@escusado aún estoy haciendo research pero si, es más el enfoque cultural. Buena idea esa, voy a buscar casos pasados de ese pedo que no hayan pegado (o que ya hayan muerto)
