### ISSUE TITLE
Your own, personal Google-like Map

### ISSUE THREAD

**Issue by escusado** [gdljs/gdljs#39]
# Your own, personal ~~Google-like~~ Map

Compartir una breve introducción a la creación de herramientas que utilicen mapas personalizados y las herramientas que existen para ayudarnos con esta tarea

## Background

Skycatch hace uso de librerías 3rd party en las que nos apoyamos para la creación y distribución de los mapas recolectados por Drone, en esta plática pretendo compartir un pequeño adelanto a Leaflet y Tilemill un par de herramientas libres que nos permitirán hacer una pequeña aplicación con mapas interactivos.

## Agenda

1. Por qué mapas?
2. De cartografías y nuevas tierras
3. Mapas hoy en día
4. Google Maps
5. Very custom maps
6. Gaming anyone?
7. Get a map
7. Tilemill
8. Simple App
9. Leaflet
10. Profit
11. Demo
12. QA

## Take Away

El acercamiento de los asistentes a usar librerías 3rd party.
Crear mapas simples y agregar complejidad usando Leaflet.

## Demo

Una pequeña aplicación donde se desplegará un mapa custom al cual le podemos agregar pines y títulos.

**Comment by pekosoG** [comment]
suena chingón! 👍
