### ISSUE TITLE
Visual programming con Blockly

### ISSUE THREAD

**Issue by rakabali78** [gdljs/gdljs#40]
# Title

Utilizando blockly en tu web-app.

## Background

Estoy desarrollando un application en donde el usuario pueda "programar" cierta parte de flujo de ejecucion, con jaavascript expression (one-liner).

Necesitamos manera mas amigable / visually-appealing para hacer esto.... Enter Blockly ( https://developers.google.com/blockly/ )

## Agenda

Ejemplo:

1. Executing JS expression in angular app (demo app.).
2. Validar JS expression en angular app. (como usar libreria JSEP para construir abstract syntax tree de la expression, y luego procesar tal AST para detectar errores).
3. Validation in place, thing should be fine now, but still user not happy, user quiere mas ayuda todavia.
4. Long story short, enter Blockly.
5. Some demo of features of Blockly.
6. QA

## Take Away

Make your app. configurable / extensible, while staying safe.

## Demo

- Demo de app. movile donde tenemos motor que dirige el flujo, y este  motor depende en estos JS expression
- Demo de web. app donde hacemos el authoring de este flujo.
- Demo de programar / extends Blockly.

**Comment by javierbyte** [comment]
interesante @rakabali78, me recuerda a un proyecto que hicimos para un hackathon: https://github.com/Holowaychitos/pereznino era un editor de chatbots con diagramas de flujo

**Comment by escusado** [comment]
El Demo suena ambicioso pero go! 👍

**Comment by rakabali78** [comment]
Aqui esta, un mejor preview del demo de la platica sobre Dockly: https://vimeo.com/205063500 … los puntos de platica seria lessons learned, and how to integrate blockly to your project (en mi caso angularjs), entre otras cosas (ideas, por ejemplo).
