### ISSUE TITLE
My experience with Legacy Code

### ISSUE THREAD

**Issue by setzer777** [gdljs/gdljs#41]
# My experience with Legacy Code

La plática se enfocará en cómo he trabajado los últimos dos años con sistemas donde mover un módulo hace que otros 4 se rompan, leer código no es placentero, pero también en qué hacer cuando estás en esa situación dependiendo de las necesidades del negocio (y cuándo hay que hacer notar eso).

## Background

Mi primera experiencia con legacy code fue en Intel, donde mantenía una herramienta muy compleja que se rompía todo el tiempo y básicamente era inmantenible.
Mi segunda experiencia fue en VoxFeed.

## Agenda

1. Teoría
  * ¿Qué es Legacy Code?
  * ¿Por qué un sistema se vuelve legacy?
2. Mi experiencia con Legacy
3. Conviviendo con legacy code
4. Analizar qué se quiere, puede, requiere o no requiere hacer.
5. Refactors y rewrites
  * Refactors con propósito.
  * El síndrome del segundo sistema
6. Buenas prácticas conviviendo con legacy code
7. Conclusión
8. Bibliografía y material
9. Demo
10. QA

## Take Away

Evitar actuar impulsivamente o tener hard feelings sobre el code base y tratar de hacer lo mejor conforme a necesidades reales. Ser más inteligentes con qué hacer refactor. *Tests 'fore refactors*

## Demo

Un refactor de un código sin pruebas transformado a un código más legible con pruebas aplicando algunas de las buenas prácticas que se presentarán. No sería como un live demo por cuestiones de tiempo.

**Comment by escusado** [comment]
Nice! se ve chida! yo digo que approves!! 👍
