### ISSUE TITLE
Javascript Fatigue

### ISSUE THREAD

**Issue by lcamargof** [gdljs/gdljs#42]
# Title
Javascript Fatigue

## Background

Desde hace unos años un tema de polemica, con tantos frameworks, boilerplates, generators, tooling uno se vuelve loco, y es algo a lo que nos enfrentamos todos en esta comunidad.
Una pequeña parte de la charla la tendria preparada, lo otro es para compartir mi experiencia como tal en esto, que es algo por lo que hemos pasado todos.

jQuery, Backbone, React, Angular, Vanilla, Webpack, boilerplate x, tool x, stack y, etc

## Agenda
1. Intro
  * Estado actual de Javascript junto a un pequeño background
  * Experiencia en los diversos stacks
  * Como no volverse loco.
2. ¿Por que?
  * Framework vs Vanilla
  * Spaguetti code
  * Pequeña demostración de dual-binding usando vueJS
3. Conclusión

## Take Away

En caso de ser nuevo, o querer entrar en este ambiente, estar preparados y tener un background de por que esta es la situación actual y de como adaptarse.
En caso de tener experiencia, apoyar su criterio sobre la situación actual, o poder discutir sobre ello.

## Demo

Solo un example de dual binding, un ejemplo muy sencillo y que podemos ver la comparacion entre vanilla y un framework.
Consistiria en definir coordenadas (en este caso left y top) de unos valores mostrados en un recuadro y dichos valores vienen de un input.
Sencillo como suena, creo que es la mejor manera de mostrar el dual binding y lo que nos ahorra.

**Comment by escusado** [comment]
Me gusta :D igual poner algo de la historia de JS :)

**Comment by sirgalleto** [comment]
Puede ser un buen complemento para la plática de [siedrix](https://speakerdeck.com/gdljs/deberia-usar-la-libreria-de-moda-en-mi-proyecto-by-at-siedrix). 

Opino lo mismo que escusado :)

**Comment by lcamargof** [comment]
Va, pero algo breve, ahi podemos estar una hora jaja, oh, supieras que si, el enfoque es un poco distinto pero la idea principal es la misma al parecer

**Comment by escusado** [comment]
yo decía por mero dato :P

**Comment by sirgalleto** [comment]
Es más para dar contexto, siempre es bueno

**Comment by rbdr** [comment]
👍 Me gusta

**Comment by orlando** [comment]
LGTM

**Comment by pekosoG** [comment]
nie 👍
