### ISSUE TITLE
Frontend tools: un viaje

### ISSUE THREAD

**Issue by CesarLanderos** [gdljs/gdljs#43]
# Frontend tools: un viaje

El mundo del frontend tiene miles de opciones en cuanto a herramientas se refiere, técnicas y estrategias que nadie consideraba usar en el mundo del html, css y js, y por esto, el mundo del Javascript sobretodo ha sido fuertemente criticado, cuando curiosamente estas técnicas se descubrieron muchos años atrás aplicadas a otros lenguajes.

## Background

Llevo casi 3 años desarrollando como frontend, en el ultimo par de años mas como fullstack, en esos 3 años casualmente e dedicado la mayoría de mi trabajo a Kimanta, la empresa donde actualmente trabajo, esta plataforma comenzó su desarrollo de manera tradicional, importando todos los archivos en el html de javascript, css y demás, después pasamos a gulp, nos emocionamos con browserify y de repente "webpack all the things"!.

Platicare que nos motivo, que beneficios nos trajo, pero sobre todo, porque y como tomamos las decisiones que nos llevo a donde estamos, y los errores que nos permitieron madurar y tener un ambiente de desarrollo estable.

## Agenda

1. Introducción
* Quien soy
* Que me inspiro a dar la platica (discusiones recientes de tooling en twitter...)

2. El orden de los factores si altera el producto
* Desarrollo tradicional, importando scrpits, un script tag por cada archivo de js
* Cuidar el orden de los archivos
* Empezar a agregar mas y mas dependencias y archivos

3. Me dijeron que la app es muy pesada, ¿y ora?
* Concatenado y minificado
* Agregando Sass como preprocesador de css

4. Creo que esto se esta poniendo complicado...
* Descubriendo los task runners y porque nos conformamos con Gulpjs
* Pipe all the things!

5. ¿Módulos? #keseso
* Descubriendo Browserify
* Descubriendo npm
* Descubriendo Babeljs

6. Mis task de repente son muy complicados e inmantenibles...
* Buscando soluciones, Webpack... se ve muy complejo, no estamos listos...
* JSPM concatena y minifica mi aplicacion, package management glory!
* uh? ¿JSPM compila mi css?, ¡wow!

7. En dev funciona, pero en produccion no
* Que funcionaba muy bien, y que cosa no funciono.
* Perdiendole el miedo a Webpack.
* Creo que Webpack es muy impresionante.
* ¿Que?, ¿Webpack compila mi css?, ya había escuchado eso, ¿y Sass, fuentes de texto, imágenes en el css y templates?
* Creo que Webpack (y simples scripts de en mi package.json) pueden reemplazar mi workflow.
* pues resulta que JSPM también puede hacer lo que Webpack hace... pero no hacen un buen trabajo vendiendo esa funcionalidad.

8. Conclucion

## Take Away

Espero que mi experiencia con estos problemas ayude a las personas que tienen opiniones fuertes en contra de las herramientas existentes en la comunidad de Javascript puedan tomar estas de manera mas tranquila por lo menos, y que las personas que recién se están enfrentando a esta avalancha de estrategias, tengan un punto de partida.

## Demo

No estoy seguro de poder realizar un demo corto, mi idea es comenzar una app con angular1 de la manera tradicional, descargando manualmente la biblioteca y comenzar a implementar un workflow con webpack y babeljs

**Comment by escusado** [comment]
Suena chido, se leé como un intro a package management y build systems.

Also creo que está un poco cargada, si te dan 20min.?

Para el demo, creo con que traigas una app super simple ya jalando (una calculadora, todolist?), para que no tengas que codear live (no interesa la app, interesa el build system creo). Así puedes mostrar la config JSPM y explicar el flow del build system y mientras lo explicas contrastarlo con webpack, no debería llevarte arriba de 5min.

De ahí en fuera me gusta!

**Comment by sirgalleto** [comment]
Me gusta bastante, me preocupa el tiempo pero el tema está muy padre.

**Comment by sirgalleto** [comment]
🎉

**Comment by CesarLanderos** [comment]
c':
