### ISSUE TITLE
Fanatismo everywhere

### ISSUE THREAD

**Issue by chukitow** [gdljs/gdljs#47]
# Fanatismo everywhere

El fanatismo es algo que vemos usualmente en temas como futbol, política, religión y hoy en día en tecnología.

Frases como: 

* **Deberias usar React, es lo de hoy.**
* **Usa Angular, si google lo usa es porque es lo mejor**
* **Critican php pero se les olvida que facebook esta programado en php**

son el argumento de hoy en día para elegir y justificar el stack de tecnología que se implementan en los proyectos dejando a un lado uno de los principios mas básico de la Ingeniería de software de software que es elegir el stack acorde a los requerimientos.

## Background

Mis primeros proyectos fueron desarrollado bajo la cortina del fanatismo usando el framework de moda y hasta hoy en día sigo limpiando esos desastres por no elegir un buen stack.  

## Agenda

1 - Introducción.
2 - ¿Qué esta pasando hoy en día?.
3 - YOU MIGHT NOT NEED JAVASCRIPT.
4 - Como funciona un framework de backend.
5 -  Como funciona un framework de frontend.
6 - Demo

## Take Away

Si hablo bien y todo sale chido por lo menos alguien entenderá como están construidos frameworks de backend, frontend y verán que usar un framework puede ser una solución a un problema que no existe.

## Demo

El demo es algo sencillo, una one single page application from scratch usando un caso práctico.

**Comment by orlando** [comment]
sounds good @chukitow, que cosa vas a mostrar en el demo que refuerce el **Take Away**

**Comment by chukitow** [comment]
Con el caso práctico @orlando, juanito(el personaje del problema) para todo quiere implementar un framework para resolver sus problemas cuando puede que realmente no lo necesita

**Comment by beeetooo** [comment]
Ponle [hype driven development](https://blog.daftcode.pl/hype-driven-development-3469fc2e9b22) a tu plática :9 just saying jaja

**Comment by sirgalleto** [comment]
👏
