### ISSUE TITLE
Build an Amazon Alexa Skill from scratch

### ISSUE THREAD

**Issue by sabs231** [gdljs/gdljs#48]
# Build an Amazon Alexa Skill from scratch

The voice enable applications are taking a big terrain for the everyday home user. It helps you with ordering different kind of products, services and even to control your home.
One of the big players on this arena is Amazon with its skills.
Skills are the applications of Amazon Echo platform, They are powered by Alexa Voice Service.
Amazon has a great platform and documentation that makes easy for developers build these skills.

On this talk I will create a skill explaining each of the steps that everyone should take to make a successful skill that will pass Amazon certification process.

## Background

Part of the team who built the Wall Street Journal Skill.
Created an internal skill for a client which needed voice authentication.
Created a quick skill for a clothe store which let's you look for items on their catalog.

## Agenda

- Introduction of Alexa skills
  - What is a skill
  - Examples of skills
- Design of an Alexa skill
  - Understanding the voice medium
  - Designing the voice UX flow
- Building an Alexa skill
  - From UX flow to interaction model
  - Implementing the skill (using AWS lambda)
    - Reason why we will use lambda
  - Skill certification process
- Next steps
- Conclusion

## Take Away

Participants will have a starting point so they can create their own alexa skills

## Demo

Demo of the built skill

**Comment by sirgalleto** [comment]
Thank you @sabs231!
