### ISSUE TITLE
Making a Twitter client for the CLI using Blessed

### ISSUE THREAD

**Issue by greduan** [gdljs/gdljs#5]
## Abstract

Talk about [Blessed](https://github.com/chjj/blessed), what it is, what it provides you, show you how to get started and maybe more real world programs, cause I find their tutorials to not show you code that you might actually use in a real app.

## Agenda

- Introduce Blessed.
- Show quick example of how to get started.
- Show how it's being used in the application.
- Mention some decisions about the Twitter client itself.

I dunno I'm not very sure how I would explain an entire app in 20 minutes, or what I should concentrate on. Ideas?

@orlando @rbdr 

Es esta platica o la otra de la DB. If you're in dire straits on talks I can do both.

**Comment by rbdr** [comment]
@greduan scheduled for november.

**Comment by greduan** [comment]
kk. Will give it to you next Monday, will work on it the weekend.

**Comment by orlando** [comment]
Closing
