### ISSUE TITLE
The age of ReasonML

### ISSUE THREAD

**Issue by charliesbox** [gdljs/gdljs#51]
# The age of ReasonML
For years, we've been extending Javascript to make it stronger and a better tool for development.
However, the challenges are bigger now. Scaling a product is not a straightforward solution.

We've been adding toolchain to the language to make it more suitable for our needs. Types, immutability and more.

The question stays, tho. Is that what we need to take our skills, scalability, and debuggability to the next level?

Let's talk about ReasonML.

## Background

Lecturer from Wizeline Academy regarding Functional Programming, which is one of the core concepts of ReasonML.

## Agenda

- Brief history of FrontEnd
- Lessons from a (really) popular library
- Can Javascript solve big problems by itself?
- ReasonML: what and why

## Take Away

Audience will learn about some core concepts of functional programming and how ReasonML fits in the FrontEnd world (and beyond)

## Demo

The demo will be a core project focused entirely on demonstrating how the code is compiled, and the development experience.

**Comment by sirgalleto** [comment]
Thanks! 🎉
