### ISSUE TITLE
 TestCafé new ui testing kid in town

### ISSUE THREAD

**Issue by Xotl** [gdljs/gdljs#54]
# [TestCafé](https://testcafe.devexpress.com) new ui testing kid in town

Lo bueno, lo malo y lo perrón de TestCafé, un framework de UI Testing.

## Background

Christian Medinilla es un desarrollador en Intersys con 7+ años de experiencia en el ramo y recientemente ha estado trabajando con TestCafé.

## Take Away

Ventajas y desventajas del framework y un pequeño demo de lo que se puede hacer.

## Demo

Un pequeño ejemplo de cómo se ve un UI Test en acción.

**Comment by escusado** [comment]
Sup, chido, podrías darnos una agenda, sólo los bulletpoints del show? nomás para que no sea un tutorial de como se usa TestCafe, igual saber nada más en que ángulo vas a explicarlo also recuerda que son 20min. sólamente. :)

**Comment by orlando** [comment]
Closing
