### ISSUE TITLE
IoT for Developers

### ISSUE THREAD

**Issue by lordzero0000** [gdljs/gdljs#55]
# IoT for Developers

Una forma sencilla de participar en el mundo de IoT cuando eres un simple desarrollador sin muchos conocimientos de electrónica.

## Background

Soy un desarrollador que tien por hobby realizar ciertos projectos de electroníca básica. 

Sinceramente creo que es un tema muy interesante y que a muchos nos podría interesar, pero en ocaciones no sabemos como empezar.

## Agenda
Ejemplo:

1. ¿Qué es IoT?
2. Electrónica y desarrolladores.
3. Tarjetas de desarrollo.
4. Demo
5. QA

## Take Away

Como crear aplicaciones sencillas para interactuar con el mundo fisico.

## Demo
Una aplicacion web por medio de la cual podran interactuar con algunos sensores.

**Comment by orlando** [comment]
Closing 👍 Gracias por la platic
