### ISSUE TITLE
Myths and legends, web performance edition

### ISSUE THREAD

**Issue by dezkareid** [gdljs/gdljs#59]
# Myths and legends, web performance edition

Una charla orientada a desenvolver ese misterioso y para algunos nuevo mundo del web performance, las consideraciones que debes tomar en cuenta para hacer optimizaciones y entender el porque debes invertir tiempo en esto si quieres un producto exitoso.

## Background

Soy instructor de una empresa llamada Centraal Academy donde estamos impartiendo temas interesantes y "complicados" a nivel técnico, hemos estado haciendo mini-proyectos acerca de performance en 3 áreas: loading, rendering y arquitectura. Hemos estado en la fase desde la preparación assets hasta el entendimiento de patrones de diseño y arquitectura orientados al performance. 

## Agenda

1. Performance
  * ¿Porqué es importante?
  * ¿Dónde puedo aplicarlo?
  * Costo VS Beneficio
2. Aspectos técnicos
  * Funcionamiento interno del navegador
  * Loading performance
  * Rendering performance
3. Herramientas para detectar issues y medir performance
  * Métricas a tomar en cuenta
  * Web API Perfomance y analytics 
  * Chrome Dev Tools
  * Webpagetest
4. Demo
5. QA

## Take Away

Entendimiento sobre todo lo que involucra el optimizar una web, cuando deben o no deben hacerlo. Las herramientas para medirlo y las métricas a considerar.

## Demo

Podrán abrir una página y auditarla, ver que elementos contienen, entender que son los números y colores que chrome nos arroja (posiblemente ahora comprendan porque devora ram)

**Comment by escusado** [comment]
Me gusta el tema bastante, me gustaría que en el Demo ver un ejemplo sencillo donde el mismo proyecto se haga con las consideraciones de optimización y una versión donde no, digo creo que quedaría más claro en lugar de abrir cualquier webpage.

**Comment by dezkareid** [comment]
@escusado  De hecho esa es la idea, voy a preparar una página que tenga un score bajo en performance y la iremos reparando, por el tiempo limitado que tengo estoy separando el ejercicio por branches para que vayan viendo que rollo en cada escenario :)
