### ISSUE TITLE
November Talk Proposal: Secure Socket.IO

### ISSUE THREAD

**Issue by iaserrat** [gdljs/gdljs#6]
This talk is meant to show techniques of authentication & authorisation in real time apps that use socket.io

Demo will be an open source chat roulette app.

**Comment by orlando** [comment]
@iaserrat can we expand on this?, I would like to have a short brief of the content and demo.

We don't have an official thing, but something in the lines of

1. Why you want to give this talk (goal for the end user)
2. Presentation content (Short brief and topics you will talk)
3. Demo content (Features it will have)
4. Is the demo "remix-able" (can the user extend it easily?)

Thanks!

**Comment by orlando** [comment]
closing this due inactivity
