### ISSUE TITLE
Serverless and Lambdas for Dum Dums

### ISSUE THREAD

**Issue by jefer590** [gdljs/gdljs#63]
# Title

Serverless and Lambdas for Dum Dums

## Background

Estoy trabajando con un proyecto que involucra tecnologias Serverless y especificamente Lambdas. Creo que compartir esta informacion seria extremadamente importante para la gente que no quiere gastar mucho dinero pero quiere empezar a sistemas entre simples y complejos

## Agenda

1. El chango que habla
 * Una pequeña introduccion sobre mi

2. Serverleque?
 * Que es Serverless
 * Filosofia de serverless development
 * Caso de Estudio de Ejemplo
 * Ejemplos de Tecnologias Serverless

3. AWS Lambda
 * Function as a Service (FaaS)
 * Que es una lambda?
 * Como funciona internamente
 * Runtimes Soportados
 * Diferentes Cosas que puedes hacer una lambda (desde programarla cada n tiempo)
 * Integraciones con AWS
 * Downsides

3. Serverless Framework
 * Que es el Serverless Framework
 * Como se instala

4. Demo

5. QA

## Take Away

Lo que aprenderá el asistente es el concepto general de las tecnologias Serverless. Se vera una de las tecnolgias mas populares Serverless (AWS Lambda) y uno de los frameworks mas populares para crear y deployar lambdas. Con ambas tecnologias, el asistente vera lo facil que es crear, integrar y deployar una lambda con Serverless Framework

## Demo

El demo será por partes. al inicio es crear el proyecto y hacer una funcion que  simplemente suma dos numeros. Se invocara la lambda manualmente para verificar que se deployó. Despues se vera como integrar una lambda con API Gateway para crear un endpoint para sumar y que este mismo invoque la funcion

**Comment by sirgalleto** [comment]
Excelente, creo que aún no se ha hablado de serverless. 

👏
