### ISSUE TITLE
¿Qué es y por qué Redux? (un acercamiento sencillo)

### ISSUE THREAD

**Issue by tonatiuh** [gdljs/gdljs#64]
# Title

¿Qué es y por qué Redux? (un acercamiento sencillo)

## Background

Desde hace algo mas de un año eh trabajado (junto con mi equipo) en migrar y extender el frontend de una aplicacion Rails/jQuery a React
- durante este tiempo de desarrollo he participado en la migración a React de alrededor de 800 archivos relacionados con vistas de Rails
- en el proceso he aprendido varias cosas, ejemplo:
  * comencé usando componentes de React que eran responsables de ambas: la logica y la UI
  * de ahí pasé a separar esos concerns, container components: un componente encargado de la lógica y otro de la UI 
  * en el momento en que las cosas se pusieron "mas complejas" comenzamos a utilizar Redux

Dar una charla sobre Redux me parece bien dado que cuando comence con React, el tema de Redux me parececía no tan claro / amigable.
Mi idea es dar una charla que de manera sencilla facilite entender que es Redux y por qué es utilizado. 

## Agenda

El contenido de la platica, puedes hacerlo algo así como un indice.

1. Que es Redux?
  * para ponernos en contexto
    * que es Redux?
    * que aporta / soluciona? 
2. Redux actions
  * que son? 
  * que funcion llevan acabo dentro de Redux
3. Redux reducers
  * que son?
  * que funcion llevan acabo dentro de Redux
4. Un caso de uso 
  * se mustra un ejemplo de un feature/tarea hecha 
    a) solo con React
    b) con React y Redux 
  * dicha tarea debera de ser una tarea que se beneficie de Redux 
    * para que de esa manera se vea el benficio de usar Redux

5. En que momento me conviene agregar Redux a mi proyecto
  * validar necesidad antes de agregar Redux
  * algunos "signos" de que tu app se beneficiaria del uso de Redux
6. Demo
  * la clásica Todo app 
    * la Todo app es fácil de "digerir"
    * el asistente (a la charla) puede profundizar más viendo el código relacionado al punto 4 (a)

## Take Away

Los asistentes a esta charla aprenderan:
  * los conceptos que component Redux
  * como se ve un feature hecho solo con React y hecho con React + Redux 
    * tendrán el código en el demo para profundizar
  * un ejemplo bien sencillo para ver como se implementa Redux 
    * se facilita comenzar con una tecnología usando un ejemplo sencillo
  * cierta noción de cuando es factible usar Redux

La idea es que la charla sea de utilidad para que quienes no han usado Redux y / o lo desconocen, se familiaricen y les facilite implementarlo.

## Demo

Tres aplicaciones pequeñas (que puedas checar en el browser out of the box)
1. un feature implementado para un caso de uso, solo con React
2. el mismo feature del punto anterior pero con React + Redux
3. un todo app (el ejemplo mas básico de los tres) con Redux

**Comment by tonatiuh** [comment]
Update: voy a incluir dos apps en el demo (en lugar de tres). Me parece que tres seria abarcar mucho / muy general.

**Comment by orlando** [comment]
@tonatiuh me gustaria ver como hacer las cosas con Redux y sin Redux.

**Comment by tonatiuh** [comment]
Hola @orlando, disculpa, no me habia percatado de tu mensaje hasta hoy.

Me late, podriamos tener una llamada en skype y discutir sobre el ejemplo que agregue aca https://github.com/tonatiuh/gdljs-redux y/o algo mas avanzado :)
