### ISSUE TITLE
[propuesta de charla] Next.js for fun and profit

### ISSUE THREAD

**Issue by soska** [gdljs/gdljs#68]
# Title

Next.js for fun and profit (título temporal, estoy en una cruzada personal por usar el menos spanglish posible )

## Background

Soy front-end developer especializado por el momento en React y he hecho algunas cosillas usando React y Next.js

## Agenda

1. Necesito un sitio web, pero no se en qué hacerlo.
 * WordPress?
 * HTML + CSS?
 * HTML + CSS + React + Node + Nginx + 💩 ?
 * create-react-app?
 * Next.js
2. Next.js in a nutshell
 * Hello world
 * Styled JSX
 * Static build
 * Custom routes
 * Deploy a Now.sh
3. Demo
 * savage.now.sh

## Take Away

Cómo es posible ir de una idea a un sitio en producción en bien poquito tiempo.

## Demo

No lo tengo listo aún, pero probablemente una variación más simple de https://github.com/soska/savagejsx

**Comment by sirgalleto** [comment]
Gracias @soska !!
