### ISSUE TITLE
Software is about people

### ISSUE THREAD

**Issue by beeetooo** [gdljs/gdljs#69]
# Software is about people

Como ingenieros de software, muchas veces nos clavamos mucho en la idea de que tenemos que dominar herramientas de programación (lenguajes, frameworks) y eso nos hará mejores devs. Una realidad que me ha tocado vivir hasta el momento es que también hay que darle enfoque a procesos de desarrollo, administración de proyectos, inteligencia emocional, entre otros soft skills. La idea general de esta platica es generar empatía ante la falta de comunicación que existen en los equipos, la mucha ambigüedad que podemos vivir, y sobre todo, darnos cuenta que, la neta, la mayor parte de los pedos que vamos a vivir en la industria son de comunicación.

## Background

Mi experiencia en este tema empieza desde hace dos años cuando trabajaba en VoxFeed, cuando empecé a agarrar skills técnicos importantes, y entre ellos empecé a conocer tecnologías chidas e ideas de diseño de software que me gustaba pensar que podían aplicar para muchos problemas. Después se remonta en Wizeline cuando empecé a vender mucho tener una arquitectura chida para los proyectos en los que trabajé, pero muchas veces la manera como lo comuniqué no fue la indicada, y en un equipo terminé siendo poco creíble, hasta hoy en día que estoy tratando de matar la ambigüedad y ser muy pro-comunicación sin molestar a todo el equipo, siendo claro y conciso, sin dejar de codear.

## Agenda

1. Entrando a la industria
  * Tecnologías por doquier
2. Hype Driven Development
  * Buzzword world (Microservices, Event Driven Architectures, Kafka, bla blah)
3. Software is about people
4. Comunicación
5. Dominios
  * Quality
  * Delivery
  * Project Management
  * Product
6. Ingeniería (no lo menos importante)

## Take Away
Mi punto de vista acerca de lo poco que conozco de la industria, y cómo podemos comunicar mejor las cosas y fomentar que la gente hable y que tengamos mejores procesos para hacer mejor software, aunque nada de esto es un silver bullet.

**Comment by sirgalleto** [comment]
Gracias @beeetooo!

**Comment by beeetooo** [comment]
De nada! Espero les haya gustado
