### ISSUE TITLE
Creando interfaces de usuario con Elm 

### ISSUE THREAD

**Issue by MachinesAreUs** [gdljs/gdljs#7]
Esta plática ya la había propuesto (y aceptaron) en ChelaJS (D.F.) pero me mudo a GDL y pues, ojalá les interese :)
https://github.com/javascriptmx/chelajs/issues/28

**Comment by pablasso** [comment]
Robandome tu outline de aquel PR:

> - ¿Por qué es interesante Elm para programadores Javascript?
- Introducción al lenguaje para programadores de Javascript.
- Creando aplicaciones web con "The Elm Architecture"
- El core de Elm: señales.
- Ejemplos divertidos de gráficos con Elm.
- Time travel debugging con Elm.
- Introduciendo Elm dentro de una aplicación Javascript.
- Comentarios sobre los beneficios de Elm.

Aquí también sería que partieras tu plática para que quede en 20 min. ¿Puedes linkear los demos que nos dijiste que ya tenías?

**Comment by MachinesAreUs** [comment]
Ok, planeo para 20 mins.
Pero por fa tengan en cuenta que no todos los temas se pueden expresar de manera adecuada en 20 mins, sobre todo si son temas donde la propuesta implica cambiar la forma de pensar que usualmente tienen. Siendo MUY exagerado, ya me imagino si a Bohr le hubieran pedido que explicara la QM en 20 mins a un grupo de físicos clásicos, y si no los convencía en ese tiempo de que era algo importante, no valía la pena hacerle caso a la QM. Es exagerado para ilustrar el punto.
El tema de Elm es algo que radicalmente cambia la manera en que se construyen aplicaciones, y además en un lenguaje que pertenece a una familia de lenguajes que funcionan radicalmente distinto a lo que la mayoría está acostumbrado. 
Aquí les dejo unos ejemplos
https://github.com/MachinesAreUs/elm_playground

**Comment by rbdr** [comment]
Estoy de acuerdo con que no puedes explicar todo en 20 minutos. Pero si no puedes partir tu tema en chunks que sean explicables en 20 minutos complementados con una demostración que los usuarios puedan hackear para aprender por su cuenta, entonces probablemente no sea un tema adecuado para nuestro evento.

**Comment by MachinesAreUs** [comment]
No hubiera intentado explicar todo aunque me dieran una hora :) Pero sí podemos experimentar partiéndolo en 2 sesiones de 20 minutos, con sus respectivos demos hackeables. Yo escojería solo los ejemplos/demos donde se pueda jugar con parámetros sin comprender aún muy bien el lenguaje.

**Comment by rbdr** [comment]
Pues eso ya sería tu decisión de que demo puede servir para entender los beneficios del lenguaje (y especialmente sin conocerlo bien como una manera de empujar a la gente a aprenderlo) o el problema que quieras resolver. Puedes tener confianza en que la comunidad va a hacer el esfuerzo y no necesita que la lleven de la mano o le avienten un tutorial, pero que le abran el camino a "Que problemas puedo resolver con esto", y le pongan un playground donde pueden tomar el resto de los pasos.

No estoy seguro de que opinen otros, pero creo que sería seguro saltarse de lo básico del lenguaje y enfocarse en lo diferente o único, lo que es común creo que lo podrían averiguar como parte del proceso.

**Comment by MachinesAreUs** [comment]
+1

**Comment by rbdr** [comment]
@MachinesAreUs no hay más updates sobre esta plática?

**Comment by MachinesAreUs** [comment]
Continúa la propuesta de darla en 2 partes, cada una con su demo :)

**Comment by MachinesAreUs** [comment]
@rbdr Alguna noticia? va?

**Comment by rbdr** [comment]
Cuales serían las dos partes? Solo lo mencionaste pero no se exactamente como va a quedar. Lo mejor sería que fueran dos partes que puedan ser aprovechadas independientemente (no va a ir la misma gente a cada sesión, entonces no estaría bueno que se quedaran con "una experiencia incompleta").

También, para tratar de dar la oportunidad de que más personas den el tema, estamos tratando de dejar unos meses de espacio entre cada presentación por la misma persona, entonces las dos pláticas estarían al menos unos 4 meses separadas.

Podrías poner una de las partes aquí y crear otro issue para la segunda, para agendarlas independientemente.

**Comment by MachinesAreUs** [comment]
Ah, hubo confusión de mi lado. La conversación respecto a darla en 2 partes fue con los de ChelaJS.
De este lado, como ya había comentado, puedo adaptarla para 20 minutos, con un demo hackeable y saltándome las partes que se parecen a lo que ya conocen.

**Comment by rbdr** [comment]
Simont, suena bien. Tienes un outline de las partes? O al menos de la primera, para ir viendo lo del scheduling :3

**Comment by orlando** [comment]
@MachinesAreUs any update on this?

**Comment by MachinesAreUs** [comment]
Sure man! andaba muy perdido en la chamba! :smile: 
El outline de esos 20 minutos es el siguiente:
1. ¿Qué problemas resuelve Elm?
2. Introducción rápida de Elm para javascripters.
3. Ejemplo de una aplicación para demostrar lo anterior y que la puedan hackear los compas.

**Comment by MachinesAreUs** [comment]
@orlando @rbdr @pablasso Entonces, va?

**Comment by orlando** [comment]
@MachinesAreUs a mi me suena bien y me gustaria para la siguiente platica, que dices @rbdr?

**Comment by rbdr** [comment]
👍

**Comment by orlando** [comment]
@MachinesAreUs te podemos agendar para la siguiente reunión que es el 29 de Marzo, te apuntas?

**Comment by MachinesAreUs** [comment]
@orlando Sí, me apunto :)

**Comment by orlando** [comment]
@MachinesAreUs awesome, esta quedaria para el 29 de Marzo. 

Por favor si puedes actualizar este issue con una descripción corta de tu platica y el titulo final. Si lo puedes hacer lo antes posible mejor :)

Gracias!

**Comment by orlando** [comment]
@MachinesAreUs Si puedes mandarle el titulo y el brief de la platica para actualizar la pagina estaria tremendo.

Tambien necesitamos tener avance de esto para el otro lunes, cualquier cosa te comunicas conmigo. Saludos!

**Comment by MachinesAreUs** [comment]
Chicos, una mala noticia.
Justo el 29 tengo que salir de viaje y regreso hasta el 1 de abril.
Una disculpa :cry:

**Comment by orlando** [comment]
@MachinesAreUs Cool no worries, Closing hasta que se vuelva a programar.
