### ISSUE TITLE
Como un galleta de la suerte me cambio la vida

### ISSUE THREAD

**Issue by striwensko** [gdljs/gdljs#72]
# Title

Como un galleta de la suerte me cambio la vida

## Background

Tengo casi 15 años de ser "freelancer" pero cuando hace un año perdi dos de mis tres principales clientes me encontre en una situación laboral muy dificil, sin embargo una galleta de la suerte fue lo que inicio un proceso en el que aun continuo de mejora constante, a lo largo de ese año hay 4 lecciones fundamentales que me han ayudado y me gustaria compartir

## Agenda

1. Suerte (La suerte no existe)
- El secreto y la ley de atraccion
- La suerte es cuando la oportunidad y la preparación se encuentran
- Tu defines que tanta suerte quieres tener si te preparas
2. Miedo (Por que el miedo es inservible)
- El miedo nos indica peligro, pero tambien nos evita llegar a nuestro maximo potencial.
- Yo y el sindrome del impostor, todos somos y no somos impostores
- Como usar el aprendizaje para superar el sindrome
3. Valor (El dinero es dinero)
- El dinero es una herramienta no un recurso
- Como transformar valor en dinero
- Por que es important aprender habilidades que te permitan aportar valor a tu entorno y no solo enfocarte en habilidades de programacion
4. Agradecimiento
- Aprender a agreder es reconocer lo bueno que tenemos
- Agradecer no es un acto de caridad es algo que te hace bien a ti

## Take Away

La conclusión es que sino trabajamos en nosotros mismos aprendiendo mas cosas no podemos crecer, y uno empieza a envejecer en el momento que deja de crecer y no solo como persona sino tambien como developer

**Comment by sirgalleto** [comment]
Estás listo para ir disfrazado a nuestra spooky version?

**Comment by rbdr** [comment]
@striwensko ping

**Comment by sirgalleto** [comment]
@striwensko Ya estás confirmado para este mes

**Comment by striwensko** [comment]
Excelente

**Comment by sirgalleto** [comment]
Thanks man
