### ISSUE TITLE
Entre JavaScripts y Machine Learnings

### ISSUE THREAD

**Issue by alexisllamas** [gdljs/gdljs#73]
# Title

Entre JavaScripts y Machine Learnings
Esta plática es para platicarles un pequeño experimento que hice, una red neuronal en vanilla JavaScript. 

## Background

Tengo más de 2 años haciendo JavaScript para el frontend y para el backend, me empecé a interesar mucho en redes neuronales y decidí aplicarlo con JavaScript.
 
## Agenda
1. Red neuronal 101
  - La definición pero sin palabras difíciles o matemáticas
2. ¿Qué vamos a construir?
  - Explicar lo qué hice
  - Cómo funciona y lo que va a hacer
3. Mi experiencia
  - Cómo logré que funcionara
  - Retos
  - Mostrar código
4. ¿Qué aprendí?
  - ¿Es víable?
  - ¿Tiene futuro?
  - ¿Qué sigue?
  - ¿Cómo empezar en machine learning si no soy un genio?
5. QA

## Take Away

Explica brevemente que van a aprender los asistentes a esta platica.

## Demo

Les voy a presentar lo que pude lograr en la Red Neuronal y cómo funciona.

**Comment by sirgalleto** [comment]
Estás listo para ir disfrazado a nuestra spooky version?

**Comment by alexisllamas** [comment]
Sí, yo me disfrazo!

**Comment by alexisllamas** [comment]
sí, ya ando preparando el disfraz 👻
