### ISSUE TITLE
Template Issues de Core

### ISSUE THREAD

**Issue by lordenzo** [gdljs/gdljs#74]
# Title

Template para issues de Core team.

## Background

En un intento por mejorar la organización interna, comenzaremos a crear issues de `core` que son cosas relacionadas con la organización de GDLJS.

## Agenda

1. Definir un draft para Issues de Core
2. Feedback y actualizaciones
3. Actualizar repo con el template

**Comment by orlando** [comment]
@lordenzo @sirgalleto podemos poner esto en un file o en otro lado?

**Comment by sirgalleto** [comment]
Cerrado por inactividad
