### ISSUE TITLE
WASM otra manera de hacer Web

### ISSUE THREAD

**Issue by yulireyji** [gdljs/gdljs#76]
A principios de este año, WebAssembly abrió irreversiblemente la Web a otros idiomas además de JavaScript. Este es un cambio con enormes consecuencias para los navegadores. Entonces, ¿qué es y  cómo funciona?

## Background

Mozilla Tech Speaker por gusto y Dessarolladora Web por que tengo malos habitos. Me gusta experimentar con nuevas técnologias, si son Open Source, mucho mejor. Es la primera vez que uso WASM.

## Agenda

- Qué es WASM?

- Cómo podrias usarlo

- JavaScritpt esta muerto?

## Take Away

Conceptos sobre WASM, como llegar a usarlo, mi historia sobre como comence a usarlo, información sobre la comunidad.

## Demo

Los demos en vivo nunca funcionan! Pero llevare una presentación muy divertida :D

**Comment by sirgalleto** [comment]
Gracias por la plática.
