### ISSUE TITLE
Damage, healer, tank. Trabajando en un equipo de desarrollo como un escuadrón RPG

### ISSUE THREAD

**Issue by chubas** [gdljs/gdljs#78]
# Title

Damage, healer, tank. Trabajando en un equipo de desarrollo como un escuadrón RPG

## Background

8+ años de experiencia trabajando en equipos de software, y probablemente más de 15 jugando juegos de estilo RPG (support main ftw)

## Agenda

1.  Un poco de game design
  * Clases, roles, habilidades
  * Balance
  * Stats y atributos
2. El equipo de desarrollo
  * El ataque
  * El tanque
  * El soporte
  * La composición
3. La estrategia
  * Objetivos
  * Balanceando el equipo
  * Cooldowns, stamina y checkpoints
 4. Q&A

## Take Away

Mejor entendimiento y algunas prácticas de team management en equipos de desarrollo usando analogías con juegos de RPG

## Demo

No habrá demo pero habrá un pequeño quiz online...

**Comment by escusado** [comment]
<3 it!

**Comment by sirgalleto** [comment]
Gracias por la plática!
