### ISSUE TITLE
from REST & ngrx/store to GraphQL - migration of Ionic Angular app

### ISSUE THREAD

**Issue by ciekawy** [gdljs/gdljs#79]
# From REST & ngrx/store to GraphQL - migration of Ionic Angular app

I am working on an after-hours mobile app project based on Ionic & parse-server. After few weeks of progress with already established tech stack and REST API I decided to migrate to Apollo GraphQL convinced by a positive experience in a daily work project.

## Background

Working @ Luxoft as a full-stack developer, personally have ~5 years experience with Angular and over a year with GraphQL (using it with both Angular and React). Also 15 years exeprience as a Java developer.

## Agenda

1. Short intro to GraphQL & Apollo
  * what is GraphQL
  * how it differ from REST
  * client features (like state management, multiple endpoints handling)
  * server features - resolvers

2. Example tech stack
  * parse-server - "backend-less"/BAAS solution
  * Ionic/Angular client
  * seamless REST integration
  * challenges with the stack

3. ngrx/store (redux) vs GraphQL Apollo client

4. Migration process

5. Outcome & benefits

4. Demo
5. QA

## Take Away

I'd like to share my experience about the benefits and challenges of using GraphQL in the project - on both backend (nodejs) and frontend. I'll also refer in particular to Apollo implementation. Last but not least I'll talk about the migration process to show what it takes to move from REST to GraphQL.

## Demo

I have a working example of my project (app is becoming an official MVP in less than a month) - will show the internals:

- how the GraphQL communication looks like
- how the state management works
- what are a cool things in the solution
- whats's still a todo
- how to start own project with similar stack

**Comment by sirgalleto** [comment]
Scheduled in [meetup](https://www.meetup.com/Guadalajara-JS/events/258312357/)
