### ISSUE TITLE
Como crear js sin librerias y no morir en el intento

### ISSUE THREAD

**Issue by striwensko** [gdljs/gdljs#8]
En esta platica planeo usar el chuba reto para explicar como crear codigo sin usar libreria alguna y a pesar de ello el codigo sea reducido y no sentir ninguna desventaja contra usar librerias avanzadas. Tratere puntos como:
1. Crear dom desde js
2. Por que los styles deben permanecer como parte de css
3. Como crear interacciones con el teclado
4. Como crear interacciones de tipo mouse y no perder tu contexto
5. Como usar prototype
6. Como crear una clase para manejar audio 
7. Como barajear los elementos de un array para que tengan un orden random

**Comment by orlando** [comment]
@striwensko 

Puedes dar mas detalles del demo?. No entiendo muy bien cual es take away de esta platica (tipo que voy a aprender). Se que es el no usar librerías, pero que ventajas me trae eso, y como se que no voy a terminar reinventando alguna librería

**Comment by striwensko** [comment]
El take away es que a veces se piensa en todo de una manera muy complicada y crear codigo sin librerias implica encontrar un approach muy sencillo para atacar los problemas. Por ejemplo en vez de incluir una libreria externa oara manejar audio por que no usar una clase de 100 lineas de codigo que funciona inlucso en mobile sin ningun problema. Y algunos trucos pueden mezclarse con la libreria de tu eleccion como en el caso de como usar scope para no perder tu contexto.

**Comment by orlando** [comment]
@striwensko todavia quieres dar esta platica?

**Comment by striwensko** [comment]
Si claro puede incluso hacerse como una platica con sesion de tips y al final un demo de todos los tips trabajando en un solo proyecto demo

**Comment by orlando** [comment]
Hey @striwensko

Si puedes responder unas preguntas sobre la platica. Tenemos un template que puedes usar para expandir un poco mas el tema y como vas a hablar de el, por favor cambia este issue para que siga ese formato https://github.com/gdljs/gdljs/blob/master/ISSUE_TEMPLATE.md

**Comment by rbdr** [comment]
Hay update aquí? @striwensko

**Comment by orlando** [comment]
@striwensko checking for updates :shipit:

**Comment by orlando** [comment]
@striwensko checando por updates, estas aca en GDLJS asi que no tienes excusas para no decirnos que pedo! u.u
