### ISSUE TITLE
Cápsulas para la memoria: la crisis del software

### ISSUE THREAD

**Issue by danielavpr** [gdljs/gdljs#81]
# Title
Cápsulas para la memoria: la crisis del software

## Background

~ año y medio trabajando en proyectos personales con equipos multidisciplinarios, casi seis meses en el mundo profesional. Estoy chiquita pero estoy aprendiendo, y quiero compartir un poco de la experiencia que he tenido y mis impresiones acerca de las metodologías y la calidad en el desarrollo del software.

## Agenda

* About me
* Primera crisis del software
* Desarrollo de metodologías de software. This is fine…o no?
* Segunda crisis del software
* There’s no silver bullet
* Las piezas son tan importantes como el todo
* Ejecuta, Aprende, Itera
* QA

## Take Away

Hacer buen software va sobre resolver problemas; no solamente los que plantea un cliente en los requerimientos, sino también los que se van generando en el propio ciclo de desarrollo. Conocer el camino que se ha recorrido hasta aquí nos ayuda a evitar cometer los mismos errores.

## Demo

No hay demo, solo una presentación bonita.

**Comment by sirgalleto** [comment]
Scheduled in [meetup](https://www.meetup.com/Guadalajara-JS/events/258312357/)
