### ISSUE TITLE
¿Por qué mi código no corre en orden? Una breve explicación del `Event Loop` en Javascript

### ISSUE THREAD

**Issue by alexescobedo** [gdljs/gdljs#83]
# Title
¿Por qué mi código no corre en orden?
Una breve explicación del `Event Loop` en Javascript

## Background

Software Engineer en Scalable Press, todo nuestro codebase esta en Javascript, Coffeescript, Typescript

## Agenda

El contenido de la platica, puedes hacerlo algo así como un indice.
* Ejemplo de código y demostración en desorden
* Fundamentos de como funciona el event loop
* Ejemplo paso a paso del funcionamiento interno

## Take Away

Explicar brevemente como funciona el event loop de node en el cual corre javascript

## Demo
No demo

**Comment by orlando** [comment]
@alexescobedo lo de no tener demo me preocupa un poco. No necesita ser un repo o algo complicado, pero si estaria cool tener algo visual para que la gente entienda como funciona.

Hable de esto hace unos años y use http://latentflip.com/loupe/ para hacer algo visual. Tambien un pequeño repo que compara como funciona golang vs nodejs https://github.com/orlando/event-loop-demo

**Comment by sirgalleto** [comment]
Muchas gracias!
