### ISSUE TITLE
JavaScript Design Patterns y porqué debería conocerlos.

### ISSUE THREAD

**Issue by NorbertCU** [gdljs/gdljs#84]
# Title

JavaScript Design Patterns y porqué debería conocerlos.

## Background

Software Engineer en Scalable Press. Former freelancer.

## Agenda

1. Qué es un Design Pattern y para qué sirve.
2. Porqué conocer los Anti-Patterns
3. Algunos ejemplos, explicaciones y código de Design Patterns

## Take Away

Explica brevemente que es un Design Pattern, para qué sirve conocerlos y dar algunos ejemplos.

## Demo

No demo.

**Comment by sirgalleto** [comment]
Muchas gracias!
