### ISSUE TITLE
El bueno, el malo y el DevOps

### ISSUE THREAD

**Issue by FerPerales** [gdljs/gdljs#85]
# Title

El bueno, el malo y el DevOps

## Background

Un día estás programando, y al otro te unes a un equipo de 3 personas encargadas de migrar cuatro aplicaciones en producción de Joyent a Azure con la misión de garantizar el mismo desempeño, pero con ahorro de costos y prácticamente cero tiempo de inactividad durante la migración.

## Agenda

1. Descripción de la misión
2. Participantes: un breve resumen de las aplicaciones a migrar
3. Stack y dependencias
4. Herramientas a utilizar
5. Los problemas encontrados y cómo resolverlos
6. Conclusiones

## Take Away

Técnicas y herramientas para hacer migraciones entre servidores de manera menos dolorosa, así como factores a considerar que olvidamos y pusieron en riesgo la misión.

## Demo

No hay un demo per se, pero la charla ya incluye partes de Ansible y de otras configuraciones.

**Comment by KarlyGrCm** [comment]
👌

**Comment by orlando** [comment]
Closing, gracias por presentar @FerPerales
