### ISSUE TITLE
Typescript para Asgardians

### ISSUE THREAD

**Issue by charliesbox** [gdljs/gdljs#86]
# Typescript para Asgardians

Probablemente ya escucharon de Typescript. Ya lo tienes en prod, ya sabes como definir strings o numbers, y seguiste paso a paso el tutorial de medium. Pero aun no estás impresionado.

Que tal si pudieramos restringir como invocar una función sin tener que correr el código? O que props puede recibir un componente?

Vamos a demostrar que la genialidad de typescript no solo viene de tener tipos, sino de restringir situaciones y mejorar el developer experience sin tener que correr un proyecto, o incluso tener que abrir otros archivos. Todo en el contexto en el que estás.

Esto no es Typescript 101 🚀

## Background

Uso typescript en mi proyecto principal, y varios side projects.

## Agenda

1. Quick intro a typescript
2. Back to the basics: porque const y let definen tipos diferentes?
3. interfaces vs types
4. Construyendo tus propios types
    - union 
    - intersections
    - discriminant unions
5. Conceptos más allá de los tutoriales

## Take Away

Los asistentes van a aprender conceptos avanzados de typescript. Para los que no lo conozcan, vamos a explorar rápidamente las ideas básicas, pero quiero abordar los conceptos complejos para mostrar el panorama de porque la industria se decanto hacia typescript.

El hype que tiene ya no es solo por moda, sino por el developer experience que ofrece inmediatamente al usarse en términos avanzados.

**Comment by orlando** [comment]
Closing. Gracias por la platica @charliesbox
