### ISSUE TITLE
Third party javascript, corriendo tu codigo en el salvaje ambiente de alguien mas. 

### ISSUE THREAD

**Issue by estavillo** [gdljs/gdljs#87]
# Title
Aprende sobre los retos en AdTech donde nosotros escribimos codigo para correr en un website que no controlamos. 

## Background

Este es un tema complicado por que tu codigo esta expuesto al codigo de otras personas, vamos a hablar sobre como hacer codigo resiliente que pueda correr en cualquier ambiente y los retos que hay que enfrentar para hacerlo

## Agenda

El contenido de la platica, puedes hacerlo algo así como un indice.

Ejemplo:

1. Third party javascript
  * Para que? 
  * Cómo?
  * Ejemplos en vivo? 
2. Writing third party javascript
  * Que retos tenemos al escribir third party javascript. 
  * Como podemos sortear estas dificultades
  * Buenas estrategias y buenas practicas para escribir third party javascript
  * Performance performance performance
3. Debugging third party javascript
  * Que herramientas podemos usar para debuggear third party javascript 
  * Herramientas locales y extensiones
  * Como medir el desempeño de mi aplicacion third party
4. Demo
5. QA

## Take Away

Escribir javascript de third party es mucho muy diferente que escribir frontend en javascript regular. Queremos que el asistente entienda estas diferencias y por que son lineas de trabajo similares pero muy diferentes.

**Comment by orlando** [comment]
Closing, gracias por la platica @estavillo
