### ISSUE TITLE
Service Worker Series ⚡️: Offline Content Caching

### ISSUE THREAD

**Issue by TheMightyPenguin** [gdljs/gdljs#88]
# Service Worker Series ⚡️: Offline Content Caching

Te haz preguntado como funciona el boton de "Read later/Save for later?" presente en algunas paginas? después de esta charla, tendrás una idea de como implementar features como ese.

En esta charla veremos como cachear contenido, en respuesta a alguna interacción del usuario.

Durante la sesión, estaremos usando [Giffr](https://giffr-3dc08.firebaseapp.com), es una aplicación de React que consume el API de Giphy. La sesión tendrá live coding, y consistirá en agregar los features necesarios para que los usuarios puedan ver sus gifs incluso cuando esten offline.

[Slides 📜](https://github.com/TheMightyPenguin/service-worker-series/tree/master/offline-content-caching)

## Background

Revise varios artículos al respecto de como mejorar la experiencia del usuario cuando esta offline, y lo agregue a un side project que tenia.

## Agenda

1. Demo de la Aplicación
2. Que es un Service Worker
    * Que podemos hacer con ellos
3. Que tenemos que hacer para agregar soporte offline en nuestra Aplicación?
4. Cachear el Application Shell
    * Que es el Application Shell?
    * Como podemos cachearlo?
    * Live coding agregando esta funcionalidad
5.  Cachear la data en JSON asociada a los gifs
    * Que mecanismos tenemos para lograr esto
    * Live coding agregando esta funcionalidad
6. Cachear las imagenes
    * `window.caches` api
    * Cuanto espacio tenemos disponible para cachear contenido
    * Live coding agregando esta funcionalidad

Cuando menciono Aplicacion en este contexto, me refiero a [Giffr](https://giffr-3dc08.firebaseapp.com), el proyecto de referencia que se estare mostrando y modificando durante la sesion.

## Take Away

Como cachear contenido offline cuando ocurre una interaccion de usuario (i.e.: Al hacer click en un boton "Read later" o "Save for later").

## Demo

El demo sera de una aplicacion de React que consume el API de Giphy, y durante la charle iremos agregando el codigo (live coding) para poder guardar los gifs favoritos del usuario, y poder mostrarlos incluso cuando el usuario este offline.

[Giffr](https://giffr-3dc08.firebaseapp.com/) 🚀

**Comment by orlando** [comment]
Closing, gracias por la platica @TheMightyPenguin
