### ISSUE TITLE
Speech Recognition API + Captions = No slides

### ISSUE THREAD

**Issue by juanjordan** [gdljs/gdljs#89]
# Speech Recognition API + Captions = No slides

En esta presentación me propongo explorar el estado del arte del Speech Recognition API y algunos usos "prácticos" que podemos darle.

## Background

Tengo 0 años de experiencia con este API pero unos cuantos programando en JavaScript y la web. Porqué? Aprender sobre este API y compartirlo con la comunidad.

## Agenda

1. Live Demo
2. Revisión del código que permite la funcionalidad
3. Live Translation
4. Con emoji

## Take Away

Speech Recognition API y `<track>` HTML element

## Demo

Live Demo

**Comment by sirgalleto** [comment]
Excelente, muchas gracias!!
