### ISSUE TITLE
Phroxy: Building a phone proxy and other stuff

### ISSUE THREAD

**Issue by iaserrat** [gdljs/gdljs#9]
Have you ever wished being able to have a disposable phone number you can give to banks or people you just don't like?  There are some services that already sell you this service, but let's build our own! (And actually is cheaper to DIY).

In this talk we will build a telephone call proxy with some other features such as caller id spoofing, programming calls with recorded audio (you won't forget say happy birthday again), recording calls, blocking numbers by regex...

All of this using node + the twilio api and a small set of rule oriented programming to build a real smartphone.

The talk will introduce the concepts behind phreaking (phone hacking), what's legal, what's not, then the demo will show the proxy working, and yes, we can make prank calls :dancers:

**Comment by orlando** [comment]
@iaserrat esto suena super cool. Me gustaría ver como va a ser el demo y como puede ser remixeable por otra gente

**Comment by rbdr** [comment]
Nice, suena muy interesante la plática, me gustaría para la sesión de enero. Igual me gustaría ver que plan tienes para el demo :D

**Comment by iaserrat** [comment]
Estoy construyendo un pequeno DSL con [nools](https://www.npmjs.com/package/nools) junto con la api de twilio de tal forma que puedas crear reglas de proxy telefonico, bloqueo de numeros basados en reglas, poner musiquita a ciertas horas/llamadas....

Para el demo la idea es presentar el DSL corriendo quiza en una raspberry o en heroku, y hacer un par de llamadas que demuestren que los core cocepts jalan, todo el proyecto seria open source para que sea jaqueable.

La estructura de la charla seria un poco asi:

- Que fue el phreaking en los 70's
- Como puede revivirse con modern apis & js
- Working Demo & code review.

**Comment by rbdr** [comment]
@iaserrat si todavía estas puesto, podemos agregarla a la sesión del 26 de enero.

**Comment by orlando** [comment]
Cerrando por falta de actividad
