### ISSUE TITLE
Si no puedo dibujarlo, es que no lo entiendo

### ISSUE THREAD

**Issue by SandraCuevas** [gdljs/gdljs#90]
# Si no puedo dibujarlo, es que no lo entiendo

Me gustaría abordar las intersecciones entre algunas expresiones artísticas y la tecnología. Desde la conceptualización de una idea, los bocetos, el prototipado, la iteración, hasta la implementación.

## Background

Mi experiencia siendo humana es de 32 años, como diseñadora 10 años, como animadora 9 años y como estudiante de front-end 4 meses

## Agenda

- Introducción
- Ejemplo Da Vinci
- Ejemplo QuemicalBros
- Ejemplo The mother of all demos
- Ejemplo FB
- Mi ejemplo

## Take Away

Lo parecido que es el proceso de programación a un proceso de producción artístico

## Demo

https://docs.google.com/presentation/d/1t_5_hjKteXN7vNg7u6CRfYLp8RRIP__09P-MKWl_fsE/edit?usp=sharing

**Comment by sirgalleto** [comment]
Muchas gracias!!
