### ISSUE TITLE
Unit testing con React hooks sin morir en el intento

### ISSUE THREAD

**Issue by arathjz** [gdljs/gdljs#91]
# Title

Como hacer test unitarios con React hooks sin morir en el intento.
Cuando hacemos test con clases usando Enzyme tenemos varias funciones que nos provee la librería para realizar nuestros test unitarios, pero...¿Qué hacemos cuando nuestro componente es funcional y usamos hooks?

## Background

Software Engineer. 100 Ladrillos.

Me gustaría hablar sobre este tema debido a que con las nuevas actualizaciones de React, creo que sería un buen aporte compartir las formas que he encontrado para realizar tests efectivos.

## Agenda

1.- Test en class components.
2.- Diferencias básicas entre class y functional components.
3.- Test en functional components con React hooks.
4.- Demo

## Take Away

Los asistentes aprenderán a hacer tests básicos utilizando React hooks y enzyme con el fin de fomentar las pruebas unitarias en el desarrollo de front end.

## Demo

Currently working on the demo 🤓

**Comment by sirgalleto** [comment]
Que gran plática, esperamos volverte a ver pronto!
