### ISSUE TITLE
Ozine.js Bringing the Joy of React Everywhere

### ISSUE THREAD

**Issue by striwensko** [gdljs/gdljs#92]
# Title

Ozine.js Bringing the Joy of React Everywhere

Ozine.js es una libreria que no remplaza ni busca remplazar a React sino todo lo contrario, la idea es llevar la filosofia de React a donde este no puede llegar. Como sitios con un backend en php, situaciones donde no se puede incluir un deploy process como sitios de shopify, o sitios con mas de 6 años de clientes que no pueden pagar por crear todo de nuevo en React. Su uso es tan sencillo y tan versatil que incluso su equivalente a Redux funciona muy bien en el propio React

## Background

Durante 15 años como desarrollador Front-end he pasado por muchas facetas, hace un par de años me desagradaban los frameworks hasta que programe en React. Su facilidad para transformar un estado en interfaz es quizas el concepto mas poderoso, incluso por encima del virtual DOM. Deslumbrado por esto decidi tomar esa filosofia y crea un pequeño framework que sin minificar cabe en una camiseta, que extrae la filosofia de React. Este approach ha sido muy versatil en distintas situaciones.

## Agenda

1. Por que React es tan Cool
2. Por que no busco remplazar ni pelear contra React, y porque llevar su filosofia fuera de el.
3) Ozine.DOM equivalente a JSX?
4) Ozine.addState equivalente a estados en React?
4) Ozine.Data equivalente a Redux, que puede ser usado incluso en React?
5) Planes a futuro

## Take Away

Por que el uso de estados es tan importante, y por que razon reinventar la rueda es la situacion perfecta para aprender.

## Demo

Como conectarse al New York Times y sacar las noticias en menos de 230 lineas de codigo? con todo y busquedas y paginado

**Comment by KarlyGrCm** [comment]
Todo se ve chido 👍  pero ya teniamos un issue abierto tuyo que cerramos por falta de actividad de tu parte (todo segun lo especificado [aquí](https://github.com/gdljs/gdljs#lifecycle-de-los-issues). Debido a que solo son 2 talks por meetup es importante para nosotros confiar en la participación de nuestros speakers. ¿Te gustaría darle seguimiento a [este issue](https://github.com/gdljs/gdljs/issues/72) primero? Así podemos tener mas seguridad de agendar tu charla y tu participación

**Comment by sirgalleto** [comment]
@striwensko estarías cómodo con agendarte el martes 27 de este mes <Agosto>?

**Comment by striwensko** [comment]
Con la que habia quedado pendiente (https://github.com/gdljs/gdljs/issues/72) que menciono @KarlyGrCm  si por que esa me la puedo aventar sin planear practicamente nada, y ya el proximo mes puedo hacer esta para con mas tiempo preparar diapositivas y sirve que termino unos tutoriales que estoy escribiendo.

**Comment by sirgalleto** [comment]
@striwensko cuándo gustas darnos esta plática?

**Comment by sirgalleto** [comment]
Cerrado por inactividad
