### ISSUE TITLE
Stalkea a tus usuarios con Google Analytics

### ISSUE THREAD

**Issue by viridianaJazel** [gdljs/gdljs#93]
# Stalkea a tus usuarios con google analytics

Nuestros usuarios puede llegar a ser ese ente indescifrable que utiliza la UI de forma misteriosa. Es un hecho que mientras mas conozcas a tus usuarios y como utilizan la UI estarás mejor equipado para tomar decisiones que te ayudarán a tener mejor tráfico y en general mejorar la usabilidad de tu sistema.

En esta plática les voy a mostrar una forma en la que puedes trackear el flujo que siguen tus usuarios, desde que entran a la UI hasta que deciden salirse, ayudándote a crear e identificar los flujos mas comunes que tus usuarios siguen, donde es mas común que se vayan o que funcionalidad es la que mas utilizan.

## Background
Soy una desarrolladora web, entusiasta de la experiencia de usuario y actualmente trabajo como Front-end en BlueOptima. Siempre he dicho que lo developers deberíamos preocuparnos de la usabilidad web para asegurarnos de que estamos entregando el mejor producto que podamos.

## Agenda
1. ¿Por qué es importante analizar qué hacen los usuarios?
2. Analizando un sitio web usando Google Analytics
  * Analicemos un pequeño sistema utilizando Google Analytics para responder a las preguntas ¿Qué están haciendo mis usuarios en la UI? ¿Están mis usuarios haciendo lo que yo definí cuando lo desarrollé? ¿Están saliendo de la página cuando no deberían?
3. Como llevar el registro de donde hacen click los usuarios.
  * Vamos a modificar el código de un sitio web para que Google Analytics pueda mostrarnos 
    los flujos.
 
## Take Away
Aprender por qué es importante analizar lo que hacen nuestros usuarios en la UI y aprender cómo puedo implementarlo en un sitio web.

## Demo
Una página con el código necesario para que Google Analytics lleve el registro de los click qué hacer el usuario en la página y que nos dibuje los flujos que siguen.

**Comment by orlando** [comment]
Esto esta muy interesante, me gustaria verla.
