### ISSUE TITLE
¿Por que Redux?

### ISSUE THREAD

**Issue by noelrock333** [gdljs/gdljs#94]
# ¿Por que Redux?

En mi platica hablo de las razones que me llevaron de odiar a Redux a realmente considerarlo como una opción para el desarrollo de aplicaciones sin caer en el exceso.

## Background

Tengo casi 4 años trabajado con aplicaciones en React de las cuales alguna que otra venían con Redux integrado pero no lograba comprender del todo la manera correcta de trabajar con esta librería y considero que así como yo debe haber muchos developers con las mismas inquietudes que tuve.

## Agenda

1. Introducción a lo que hago
2. Redux
  * Para que sirve y que podemos hacer con el
  * ¿En dónde lo podemos usar?
  * Una historia de lo que me hizo cambiar de opinión.
  * Explicación de ejemplo sencillo
2. Despedida

## Take Away

Los asistentes aprenderán a distinguir en que casos de uso es correcto usar Redux y cómo perderle el miedo a esta librería que parece super complicada sobre todo para los principiantes.

## Demo

Será una aplicación super sencilla de al menos 3 componentes que interactúan entre ellos compartiendo estado y el history del router la cual ya estará lista solo para ser levantada con un 
`yarn start`.

**Comment by sirgalleto** [comment]
🙏
