### ISSUE TITLE
 Un ORM en el Front-end con schemas para Redux

### ISSUE THREAD

**Issue by contrerasjf0** [gdljs/gdljs#95]
# Title

Un ORM en el Front-end con schemas para Redux

## Background

He sido fullstack developer y he trabajado con diferentes lenguajes y tecnologías, siempre me llama la atención aprender patrones de diseños, arquitecturas, etc.. que se adecuen a las necesidades, tiempo, características, etc. del proyecto en el que estoy trabajando; una de estas busquedas y la necesidad de normalizar mis datos me llevo a encontrarme con Redux-ORM una librería que nos permite normalizar datos con schemas y así poder implementar una abstracción de un ORM con nuestros datos en el Redux storage. 

Front-end coach en Laboratoria

## Agenda

1.- Principios y Fundamentos de Redux
2.- Que es normalizar datos
3.- Que es un ORM
4.- Redux-ORM
5.- Ventajas
6.- Demo

## Take Away

La comunidad presente podrán conocer una de tantas maneras de manejar uno de los principios de Redux, que es la normalización de datos y su importancia.

## Demo

Se mostrara una sencilla aplicación que implementara Redux-ORM para almacenar libros, autores y clasificaciones en el Redux storage.

**Comment by sirgalleto** [comment]
Miiil gracias!
