### ISSUE TITLE
A-Frame! 3D pero como con React

### ISSUE THREAD

**Issue by escusado** [gdljs/gdljs#96]
# A-Frame! 3D pero como con React

Un overview de este framework para hacer objectos en 3D que sigue folosofias interesantes de cómo mentalizar una arquitectura.

## Background

La plática está pensada para todos los niveles

## Agenda

A-Frame
Por que?
Cómo convive con ThreeJS
Cómo combinarlo con React
Es necesario?
La magia que es el Entity Component System
Por que quieres lógica aparte de tu DOM?
VR!

## Take Away

Una manera fácil de hacer 3D muy rápido.

## Demo

A very simple scene that explains everything

**Comment by sirgalleto** [comment]
Thank you master!
