### ISSUE TITLE
a11y, o como no romper el internet

### ISSUE THREAD

**Issue by rbdr** [gdljs/gdljs#97]
# a11y, o como no romper el internet

Un tour de como el internet está roto para millones de personas y que podemos hacer para cambiarlo.

## Background

Llevo años haciendo web apps pero lamentablemente solo poco tiempo considerando la accesibilidad de estas aplicaciones, quiero compartir algo de lo que he aprendido.

## Agenda

* El internet a través de varios tipos de discapacidad
  * Visuales
  * Auditivas
  * Motrices
  * Cognitivas
* Herramientas para no romper el internet
  * ARIA / HTML semántico
  * Texto, el viejo confiable
  * Formas de interactuar
  * Simplicidad, no solo por estética

## Take Away

Gran parte del internet está roto para muchas personas: ¿Qué prácticas podemos adoptar para arreglarlo y hacerlo más inclusivo?

## Demo

Un web app que usa varias de estas herramientas.

**Comment by sirgalleto** [comment]
@rbdr cuándo puedes dar la plática?

**Comment by sirgalleto** [comment]
Siempre es un placer tenerte como speaker
