### ISSUE TITLE
Harakiri (o no) haciendo pruebas end to end con Cypress IO 

### ISSUE THREAD

**Issue by heryxpc** [gdljs/gdljs#98]
# Title

Harakiri (o no) haciendo pruebas end to end con [Cypress.io](https://www.cypress.io/) 

## Background

Actualmente en [helix.re](https://helix.re) estamos utilizando Cypress para realizar nuestras pruebas de regresión. Nuestra plataforma web esta hecha en React con una gestión de estados crítica para su funcionamiento y manejando subida/descarga de archivos de hasta 30 GiB. Dado que no tenemos un equipo de QA dedicado, nos dimos a la tarea de automatizar en lo posible las pruebas de regresión. Yo tome el reto de darle mantenimiento a esas pruebas para hacerlas útiles en nuestros procesos de CI/CD.

## Agenda

1.  Que es Cypress
* Donde encontrar documentación
* Como funciona
* Como NO funciona
2. Retos de las pruebas end to end
* Manejo de estados asíncronos
* Interacción con APIs
* Datos de prueba
* Integración continua
3. Como morir con honor con Cypress
* seppuku 切腹 - modificar el DOM
* setsu 切 - stubbing de los API
* harakiri 腹切り - limpiar tus pruebas con + pruebas
* oibara 追腹 - fallar tu pipeline por tus pruebas
4. Lecciones aprendidas
5. Q & A

## Take Away

Retos técnicos de utilizar Cypress como el extenderlo, manejar archivos de prueba, crear selectores adecuados. También el que considerar al elegir una estrategia de automatización de pruebas en ambientes de integración continua.

## Demo

Mostraré un demo de nuestro código actual de pruebas y una comparativa de cómo ha ido evolucionando a partir que lo estamos utilizando como nuestro _gateway_ en cada liberación.

**Comment by heryxpc** [comment]
Los slides están en:[https://www.slideshare.net/secret/eJUBSXSJ36xEif](https://www.slideshare.net/secret/eJUBSXSJ36xEif)

**Comment by sirgalleto** [comment]
Gracias!!
